### ISSUE TITLE
OnscreenText setPos does something different than set_pos

### ISSUE THREAD

**Issue by tcdude** [panda3d/panda3d#1041]
## Description
The `OnscreenText` widget appears to handle calls to `setPos()` differently than it does `set_pos()`,
the former expects two floats for x/y while the latter appears to behave as if it were a `NodePath`.

Using it wrong leads to this error:
```
Traceback (most recent call last):
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "onsctxt.py", line 26, in displayText
    self.textName.setPos(self.textName, Vec3(0, 0, 0.1))
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/gui/OnscreenText.py", line 326, in setPos
    self.updateTransformMat()
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/gui/OnscreenText.py", line 365, in updateTransformMat
    Mat4.translateMat(Point3.rfu(self.__pos[0], 0, self.__pos[1]))
TypeError: must be real number, not OnscreenText
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "onsctxt.py", line 30, in <module>
    game.run()
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 3319, in run
    self.taskMgr.run()
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/task/Task.py", line 541, in run
    self.step()
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/task/Task.py", line 495, in step
    self.mgr.poll()
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "onsctxt.py", line 26, in displayText
    self.textName.setPos(self.textName, Vec3(0, 0, 0.1))
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/gui/OnscreenText.py", line 326, in setPos
    self.updateTransformMat()
  File "/home/tc/tmp/venv/lib/python3.8/site-packages/direct/gui/OnscreenText.py", line 365, in updateTransformMat
    Mat4.translateMat(Point3.rfu(self.__pos[0], 0, self.__pos[1]))
TypeError: must be real number, not OnscreenText
```

## Steps to Reproduce
```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import TextNode, Vec3
from direct.gui.OnscreenText import OnscreenText

class Game(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        
        self.textName = OnscreenText(text = "Old text", fg = (1, 1, 1, 1), align = TextNode.ACenter, scale = 0.1)
        
        # Press the key p
        base.accept('p', self.displayText)

    def displayText(self):
        self.textName.text = "New text"
        
        # setPos works like this:
        self.textName.setPos(0, 0.1)
        # but fails if used like a NodePath (e.g. setPos(other, x, y, z) throws an error)
        
        # set_pos behaves like a NodePath and works as expected
        self.textName.set_pos(self.textName, Vec3(0, 0, 0.1))  # changing this to use setPos instead crashes


game = Game()
game.run()
```

## Environment
 * Operating system: Linux
 * System architecture: x64
 * Panda3D version: 1.10.7
 * Installation method: pip
 * Python version (if using Python): 3.8.5

**Comment by rdb** [comment]
The set_pos comes from NodePath, whereas OnscreenText overrides setPos to something that takes only an x, y.

For compatibility we should define a set_pos that works with either signature.

**Comment by rdb** [comment]
This problem is even hairier and more annoying than I thought.  OnscreenText's setPos does something very different than NodePath's setPos: the former actually controls a special transform on the TextNode that is separate from the one on the node itself.  Ugh.

In the long run we need to fix this by clearly disambiguating between the two.  I need to think about how we'll fix this in 1.10.8 neatly—there may not be a clean way.

**Comment by rdb** [comment]
So, what's going on here is that there are two positions, one is applied only to the text, and the other is applied to the node (via set_pos).  Confusingly, OnscreenText overrides setPos (but not set_pos) to set the text transform instead of the node transform.

I think we have to more clearly decouple these in the API.  What I think we should do is this:
- [x] In 1.10.8, add a setTextPos / text_pos alias for setPos.
- [ ] In 1.11.0, deprecate setPos in favour of setTextPos / text_pos.
- [ ] In 2.0.0, remove setPos, only leaving the now-unambiguous `set_pos()` and `text_pos`.

**Comment by serkkz** [comment]
Need more radical methods, just get rid of OnscreenText, recommend TextNode instead.

**Comment by ArsThaumaturgis** [comment]
OnscreenText has the advantage of being quick and easy: If you just want to throw some text onto the screen, and don't have any more-complex requirements, it's that little bit easier to use OnscreenText than a raw TextNode. They both have their uses, I feel.

**Comment by serkkz** [comment]
I suggest to compare:
```py
label_node  = OnscreenText()
label_node .setName('label')
label_node .node().setText('text string')
```
Or:
```py
label = TextNode('label')
label.setText('text string')  
label_node = NodePath(label.generate())
label_node.reparentTo(aspect2d)
```
The difference is that you have to choose the node where to attach it.  As for the OnscreenText parameters, I think the user himself is able to write the constructor class for TextNode.

1. This step will reduce the dependence on direct.
2. It is enough to have one instance of TextNode to create different labels.
```py
label = TextNode('label')

label.setText('text string')  
label_node = NodePath(label.generate())
label_node.reparentTo(aspect2d)

label.setText('text string1')  
label_node1 = NodePath(label.generate())
label_node1.reparentTo(aspect2d)
```
3. It looks the same as in C++, which is syntactically legible regardless of the language.

**Comment by ArsThaumaturgis** [comment]
Except that your first example can be largely compressed down to a single line:
```python
label = OnscreenText(text = "text string")
```
I'll admit that the name is left off--but then, I've seldom found that important in such elements.

> As for the OnscreenText parameters, I think the user himself is able to write the constructor class for TextNode.

Often enough true--but perhaps less so for newcomers, who may benefit the most from the presence of a convenience wrapper to TextNode.

(I've actually written a function for conveniently generating TextNodes myself--but even so, when throwing a simply counter onto the screen for a side-project, I find it more convenient to just use an OnscreenText object.)

> This step will reduce the dependence on direct.

That's a fair point--but I'd rather OnscreenText were moved out of "direct" than dropped entirely if the removal of direct is desired.

> It is enough to have one instance of TextNode to create different labels.

I'll confess that I didn't know that this was an available feature. But then, I'm also not sure of the advantage...?

> It looks the same as in C++, syntactically legible regardless of the language.

Hmm... I suppose that this is an advantage. It's not one that bothers me overmuch, but it may be important to others.

**Comment by rdb** [comment]
This is not a forum to discuss the merits of OnscreenText as a whole, but an issue to discuss the discrepancy in behaviour of setPos versus set_pos.  I suggest continuing this debate in a Discourse thread, or, a new issue proposing the removal of OnscreenText.

**Comment by ArsThaumaturgis** [comment]
Okay, fair--my apologies for my part.

**Comment by BMaxV** [comment]
I dislike removing `setPos` because it's convention in panda that that's the name of the function that sets positions.

I am more interested to understand what `.__pos` is to a textnode and why that's necessary to set the position.
