### ISSUE TITLE
Crash when pressing gamepad dpad buttons

### ISSUE THREAD

**Issue by K9Kraken** [panda3d/panda3d#1066]
## Description
(I have tested this on a couple different computers running Manjaro with the same result)
Using an Xbox 360 wireless gamepad with USB dongle.
Using code to attach the gamepad:
```
        gamepads = base.devices.get_devices(InputDevice.DeviceClass.gamepad)
        self.attach_input_device(gamepads[0], prefix="gamepad")
```
When pressing any DPAD key panda3D will crash, all other buttons work fine.
Sometimes after rebooting computer and starting panda it will work fine and I can read the dpad input just fine, but after restarting panda3d it will crash.
Issue still happens when connecting the controller after panda starts and using code that detects connected devices and runs code above.
If you comment out the `self.attach_input_device(gamepads[0], prefix="gamepad")` line Panda will not crash when pressing buttons.
**Console output:**
```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Assertion failed: code >= 0 && (size_t)code < _button_indices.size() at line 817 of panda/src/device/evdevInputDevice.cxx
Traceback (most recent call last):
  File "/home/will/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 2091, in __dataLoop
    self.dgTrav.traverse(self.dataRootNode)
AssertionError: code >= 0 && (size_t)code < _button_indices.size() at line 817 of panda/src/device/evdevInputDevice.cxx
:task(error): Exception occurred in PythonTask dataLoop
Traceback (most recent call last):
  File "/home/will/Sync/projects/panda/bug_test/dpad_crash.py", line 13, in <module>
    app.run()
  File "/home/will/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 3319, in run
    self.taskMgr.run()
  File "/home/will/.local/lib/python3.8/site-packages/direct/task/Task.py", line 541, in run
    self.step()
  File "/home/will/.local/lib/python3.8/site-packages/direct/task/Task.py", line 495, in step
    self.mgr.poll()
  File "/home/will/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 2091, in __dataLoop
    self.dgTrav.traverse(self.dataRootNode)
AssertionError: code >= 0 && (size_t)code < _button_indices.size() at line 817 of panda/src/device/evdevInputDevice.cxx
[Finished in 3.3s with exit code 1]
[cmd: ['python', '-u', '/home/will/Sync/projects/panda/bug_test/dpad_crash.py']]
[dir: /home/will/Sync/projects/panda/bug_test]
[path: /home/will/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin]
```

## Steps to Reproduce
Connect and turn on 360 xbox controller then run panda with the code bellow, press one of the depad buttons and Panda3D will crash, if not then restart panda and try again.
```
from direct.showbase.ShowBase import ShowBase
from panda3d.core import InputDevice


class MyApp(ShowBase):

    def __init__(self):
        ShowBase.__init__(self)
        gamepads = base.devices.get_devices(InputDevice.DeviceClass.gamepad)
        self.attach_input_device(gamepads[0], prefix="gamepad")

app = MyApp()
app.run()
```

## Environment
 * Operating system: 5.9.11-3-MANJARO
 * System architecture: X86_64
 * Panda3D version: 1.10.7
 * Installation method: PIP and also tested building from source
 * Python version 3.8.6

**Comment by K9Kraken** [comment]
I tested a Switch Pro controller and so far it is working just fine.

**Comment by rdb** [comment]
Please attach the crashing output with only the malfunctioning device plugged in and `notify-level-device spam` set.

**Comment by K9Kraken** [comment]
```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:device(debug): Unmapped /dev/input/event0 button 0: 0x8e
:device(debug): Discovered evdev input device Sleep Button (connected), 1 button
:device(debug): Unmapped /dev/input/event1 button 0: 0x74
:device(debug): Discovered evdev input device Power Button (connected), 1 button
:device(debug): Unmapped /dev/input/event2 button 0: 0x74
:device(debug): Discovered evdev input device Power Button (connected), 1 button
:device(debug): Discovered evdev input device PC Speaker (connected)
:device(debug): Discovered evdev input device HDA NVidia HDMI/DP,pcm=3 (connected)
:device(debug): Discovered evdev input device HDA NVidia HDMI/DP,pcm=7 (connected)
:device(debug): Discovered evdev input device HDA NVidia HDMI/DP,pcm=8 (connected)
:device(debug): Discovered evdev input device HDA NVidia HDMI/DP,pcm=9 (connected)
:device(debug): Discovered evdev input device HDA NVidia HDMI/DP,pcm=10 (connected)
:device(debug): Discovered evdev input device HDA NVidia HDMI/DP,pcm=11 (connected)
:device(debug): Discovered evdev input device HDA NVidia HDMI/DP,pcm=12 (connected)
:device(debug): Discovered evdev input device HDA Intel PCH Front Mic (connected)
:device(debug): Discovered evdev input device HDA Intel PCH Rear Mic (connected)
:device(debug): Discovered evdev input device HDA Intel PCH Line (connected)
:device(debug): Discovered evdev input device HDA Intel PCH Line Out Front (connected)
:device(debug): Discovered evdev input device HDA Intel PCH Line Out Surround (connected)
:device(debug): Discovered evdev input device HDA Intel PCH Line Out CLFE (connected)
:device(debug): Discovered evdev input device HDA Intel PCH Front Headphone (connected)
:device(debug): Unmapped /dev/input/event18 button 1: 0x71
:device(debug): Unmapped /dev/input/event18 button 2: 0x72
:device(debug): Unmapped /dev/input/event18 button 3: 0x73
:device(debug): Unmapped /dev/input/event18 button 4: 0x8b
:device(debug): Unmapped /dev/input/event18 button 5: 0x94
:device(debug): Unmapped /dev/input/event18 button 6: 0x98
:device(debug): Unmapped /dev/input/event18 button 7: 0xab
:device(debug): Unmapped /dev/input/event18 button 8: 0xac
:device(debug): Unmapped /dev/input/event18 button 9: 0xb8
:device(debug): Unmapped /dev/input/event18 button 10: 0xb9
:device(debug): Unmapped /dev/input/event18 button 11: 0xd4
:device(debug): Unmapped /dev/input/event18 button 12: 0xe0
:device(debug): Unmapped /dev/input/event18 button 13: 0xe1
:device(debug): Unmapped /dev/input/event18 button 14: 0xe3
:device(debug): Unmapped /dev/input/event18 button 15: 0xee
:device(debug): Unmapped /dev/input/event18 button 16: 0xf0
:device(debug): Unmapped /dev/input/event18 button 17: 0x1af
:device(debug): Discovered evdev input device Eee PC WMI hotkeys (connected), 18 buttons
:device(debug): Unmapped /dev/input/event19 button 83: 0x55
:device(debug): Unmapped /dev/input/event19 button 84: 0x56
:device(debug): Unmapped /dev/input/event19 button 87: 0x59
:device(debug): Unmapped /dev/input/event19 button 88: 0x5a
:device(debug): Unmapped /dev/input/event19 button 89: 0x5b
:device(debug): Unmapped /dev/input/event19 button 90: 0x5c
:device(debug): Unmapped /dev/input/event19 button 91: 0x5d
:device(debug): Unmapped /dev/input/event19 button 92: 0x5e
:device(debug): Unmapped /dev/input/event19 button 93: 0x5f
:device(debug): Unmapped /dev/input/event19 button 109: 0x71
:device(debug): Unmapped /dev/input/event19 button 110: 0x72
:device(debug): Unmapped /dev/input/event19 button 111: 0x73
:device(debug): Unmapped /dev/input/event19 button 112: 0x74
:device(debug): Unmapped /dev/input/event19 button 113: 0x75
:device(debug): Unmapped /dev/input/event19 button 115: 0x78
:device(debug): Unmapped /dev/input/event19 button 116: 0x79
:device(debug): Unmapped /dev/input/event19 button 117: 0x7a
:device(debug): Unmapped /dev/input/event19 button 118: 0x7b
:device(debug): Unmapped /dev/input/event19 button 119: 0x7c
:device(debug): Unmapped /dev/input/event19 button 123: 0x80
:device(debug): Unmapped /dev/input/event19 button 124: 0x81
:device(debug): Unmapped /dev/input/event19 button 125: 0x82
:device(debug): Unmapped /dev/input/event19 button 126: 0x83
:device(debug): Unmapped /dev/input/event19 button 127: 0x84
:device(debug): Unmapped /dev/input/event19 button 128: 0x85
:device(debug): Unmapped /dev/input/event19 button 129: 0x86
:device(debug): Unmapped /dev/input/event19 button 130: 0x87
:device(debug): Unmapped /dev/input/event19 button 131: 0x88
:device(debug): Unmapped /dev/input/event19 button 132: 0x89
:device(debug): Unmapped /dev/input/event19 button 133: 0x8a
:device(debug): Unmapped /dev/input/event19 button 134: 0x8b
:device(debug): Unmapped /dev/input/event19 button 135: 0x8c
:device(debug): Unmapped /dev/input/event19 button 136: 0x8e
:device(debug): Unmapped /dev/input/event19 button 137: 0x8f
:device(debug): Unmapped /dev/input/event19 button 138: 0x90
:device(debug): Unmapped /dev/input/event19 button 139: 0x96
:device(debug): Unmapped /dev/input/event19 button 140: 0x98
:device(debug): Unmapped /dev/input/event19 button 141: 0x9b
:device(debug): Unmapped /dev/input/event19 button 142: 0x9c
:device(debug): Unmapped /dev/input/event19 button 144: 0x9f
:device(debug): Unmapped /dev/input/event19 button 145: 0xa1
:device(debug): Unmapped /dev/input/event19 button 146: 0xa3
:device(debug): Unmapped /dev/input/event19 button 147: 0xa4
:device(debug): Unmapped /dev/input/event19 button 148: 0xa5
:device(debug): Unmapped /dev/input/event19 button 149: 0xa6
:device(debug): Unmapped /dev/input/event19 button 150: 0xa7
:device(debug): Unmapped /dev/input/event19 button 151: 0xa8
:device(debug): Unmapped /dev/input/event19 button 152: 0xa9
:device(debug): Unmapped /dev/input/event19 button 153: 0xab
:device(debug): Unmapped /dev/input/event19 button 154: 0xac
:device(debug): Unmapped /dev/input/event19 button 155: 0xad
:device(debug): Unmapped /dev/input/event19 button 156: 0xae
:device(debug): Unmapped /dev/input/event19 button 157: 0xb0
:device(debug): Unmapped /dev/input/event19 button 158: 0xb1
:device(debug): Unmapped /dev/input/event19 button 159: 0xb2
:device(debug): Unmapped /dev/input/event19 button 160: 0xb3
:device(debug): Unmapped /dev/input/event19 button 161: 0xb4
:device(debug): Unmapped /dev/input/event19 button 162: 0xb5
:device(debug): Unmapped /dev/input/event19 button 163: 0xb6
:device(debug): Unmapped /dev/input/event19 button 164: 0xb7
:device(debug): Unmapped /dev/input/event19 button 165: 0xb8
:device(debug): Unmapped /dev/input/event19 button 166: 0xb9
:device(debug): Unmapped /dev/input/event19 button 167: 0xba
:device(debug): Unmapped /dev/input/event19 button 168: 0xbb
:device(debug): Unmapped /dev/input/event19 button 169: 0xbc
:device(debug): Unmapped /dev/input/event19 button 170: 0xbd
:device(debug): Unmapped /dev/input/event19 button 171: 0xbe
:device(debug): Unmapped /dev/input/event19 button 172: 0xbf
:device(debug): Unmapped /dev/input/event19 button 173: 0xc0
:device(debug): Unmapped /dev/input/event19 button 174: 0xc1
:device(debug): Unmapped /dev/input/event19 button 175: 0xc2
:device(debug): Unmapped /dev/input/event19 button 176: 0xce
:device(debug): Unmapped /dev/input/event19 button 177: 0xcf
:device(debug): Unmapped /dev/input/event19 button 178: 0xd0
:device(debug): Unmapped /dev/input/event19 button 179: 0xd1
:device(debug): Unmapped /dev/input/event19 button 180: 0xd2
:device(debug): Unmapped /dev/input/event19 button 181: 0xd4
:device(debug): Unmapped /dev/input/event19 button 182: 0xd8
:device(debug): Unmapped /dev/input/event19 button 184: 0xdb
:device(debug): Unmapped /dev/input/event19 button 185: 0xdf
:device(debug): Unmapped /dev/input/event19 button 186: 0xe0
:device(debug): Unmapped /dev/input/event19 button 187: 0xe1
:device(debug): Unmapped /dev/input/event19 button 188: 0xe4
:device(debug): Unmapped /dev/input/event19 button 189: 0xe5
:device(debug): Unmapped /dev/input/event19 button 190: 0xe6
:device(debug): Unmapped /dev/input/event19 button 191: 0xe7
:device(debug): Unmapped /dev/input/event19 button 192: 0xe8
:device(debug): Unmapped /dev/input/event19 button 193: 0xe9
:device(debug): Unmapped /dev/input/event19 button 194: 0xea
:device(debug): Unmapped /dev/input/event19 button 195: 0xeb
:device(debug): Unmapped /dev/input/event19 button 196: 0xf0
:device(debug): Unmapped /dev/input/event19 button 197: 0xf1
:device(debug): Unmapped /dev/input/event19 button 198: 0xf4
:device(debug): Unmapped /dev/input/event19 button 199: 0x100
:device(debug): Unmapped /dev/input/event19 button 205: 0x115
:device(debug): Unmapped /dev/input/event19 button 206: 0x116
:device(debug): Unmapped /dev/input/event19 button 207: 0x117
:device(debug): Unmapped /dev/input/event19 button 208: 0x118
:device(debug): Unmapped /dev/input/event19 button 209: 0x119
:device(debug): Unmapped /dev/input/event19 button 210: 0x11a
:device(debug): Unmapped /dev/input/event19 button 211: 0x11b
:device(debug): Unmapped /dev/input/event19 button 212: 0x11c
:device(debug): Unmapped /dev/input/event19 button 213: 0x11d
:device(debug): Unmapped /dev/input/event19 button 214: 0x11e
:device(debug): Unmapped /dev/input/event19 button 215: 0x11f
:device(debug): Unmapped /dev/input/event19 button 216: 0x161
:device(debug): Unmapped /dev/input/event19 button 217: 0x162
:device(debug): Unmapped /dev/input/event19 button 218: 0x166
:device(debug): Unmapped /dev/input/event19 button 219: 0x16a
:device(debug): Unmapped /dev/input/event19 button 220: 0x16e
:device(debug): Unmapped /dev/input/event19 button 221: 0x172
:device(debug): Unmapped /dev/input/event19 button 222: 0x174
:device(debug): Unmapped /dev/input/event19 button 223: 0x176
:device(debug): Unmapped /dev/input/event19 button 224: 0x177
:device(debug): Unmapped /dev/input/event19 button 225: 0x178
:device(debug): Unmapped /dev/input/event19 button 226: 0x179
:device(debug): Unmapped /dev/input/event19 button 227: 0x17a
:device(debug): Unmapped /dev/input/event19 button 228: 0x17b
:device(debug): Unmapped /dev/input/event19 button 229: 0x17c
:device(debug): Unmapped /dev/input/event19 button 230: 0x17d
:device(debug): Unmapped /dev/input/event19 button 231: 0x17f
:device(debug): Unmapped /dev/input/event19 button 232: 0x180
:device(debug): Unmapped /dev/input/event19 button 233: 0x182
:device(debug): Unmapped /dev/input/event19 button 234: 0x183
:device(debug): Unmapped /dev/input/event19 button 235: 0x185
:device(debug): Unmapped /dev/input/event19 button 236: 0x188
:device(debug): Unmapped /dev/input/event19 button 237: 0x189
:device(debug): Unmapped /dev/input/event19 button 238: 0x18c
:device(debug): Unmapped /dev/input/event19 button 239: 0x18d
:device(debug): Unmapped /dev/input/event19 button 240: 0x18e
:device(debug): Unmapped /dev/input/event19 button 241: 0x18f
:device(debug): Unmapped /dev/input/event19 button 242: 0x190
:device(debug): Unmapped /dev/input/event19 button 243: 0x191
:device(debug): Unmapped /dev/input/event19 button 244: 0x192
:device(debug): Unmapped /dev/input/event19 button 245: 0x193
:device(debug): Unmapped /dev/input/event19 button 246: 0x195
:device(debug): Unmapped /dev/input/event19 button 248: 0x198
:device(debug): Unmapped /dev/input/event19 button 249: 0x199
:device(debug): Unmapped /dev/input/event19 button 250: 0x19a
:device(debug): Unmapped /dev/input/event19 button 252: 0x1a0
:device(debug): Unmapped /dev/input/event19 button 253: 0x1a1
:device(debug): Unmapped /dev/input/event19 button 254: 0x1a2
:device(debug): Unmapped /dev/input/event19 button 255: 0x1a3
:device(debug): Unmapped /dev/input/event19 button 256: 0x1a4
:device(debug): Unmapped /dev/input/event19 button 257: 0x1a5
:device(debug): Unmapped /dev/input/event19 button 258: 0x1a6
:device(debug): Unmapped /dev/input/event19 button 259: 0x1a7
:device(debug): Unmapped /dev/input/event19 button 260: 0x1a8
:device(debug): Unmapped /dev/input/event19 button 261: 0x1a9
:device(debug): Unmapped /dev/input/event19 button 262: 0x1aa
:device(debug): Unmapped /dev/input/event19 button 263: 0x1ab
:device(debug): Unmapped /dev/input/event19 button 264: 0x1ac
:device(debug): Unmapped /dev/input/event19 button 265: 0x1ad
:device(debug): Unmapped /dev/input/event19 button 266: 0x1ae
:device(debug): Unmapped /dev/input/event19 button 267: 0x1af
:device(debug): Unmapped /dev/input/event19 button 268: 0x1b0
:device(debug): Unmapped /dev/input/event19 button 269: 0x1b1
:device(debug): Unmapped /dev/input/event19 button 270: 0x1b7
:device(debug): Unmapped /dev/input/event19 button 271: 0x1ba
:device(debug): Discovered evdev input device Logitech MX Keys (connected), 272 buttons, 1 axis, pointer, keyboard
:device(debug): Unmapped /dev/input/event20 button 83: 0x55
:device(debug): Unmapped /dev/input/event20 button 84: 0x56
:device(debug): Unmapped /dev/input/event20 button 87: 0x59
:device(debug): Unmapped /dev/input/event20 button 88: 0x5a
:device(debug): Unmapped /dev/input/event20 button 89: 0x5b
:device(debug): Unmapped /dev/input/event20 button 90: 0x5c
:device(debug): Unmapped /dev/input/event20 button 91: 0x5d
:device(debug): Unmapped /dev/input/event20 button 92: 0x5e
:device(debug): Unmapped /dev/input/event20 button 93: 0x5f
:device(debug): Unmapped /dev/input/event20 button 109: 0x71
:device(debug): Unmapped /dev/input/event20 button 110: 0x72
:device(debug): Unmapped /dev/input/event20 button 111: 0x73
:device(debug): Unmapped /dev/input/event20 button 112: 0x74
:device(debug): Unmapped /dev/input/event20 button 113: 0x75
:device(debug): Unmapped /dev/input/event20 button 115: 0x79
:device(debug): Unmapped /dev/input/event20 button 116: 0x7a
:device(debug): Unmapped /dev/input/event20 button 117: 0x7b
:device(debug): Unmapped /dev/input/event20 button 118: 0x7c
:device(debug): Unmapped /dev/input/event20 button 122: 0x80
:device(debug): Unmapped /dev/input/event20 button 123: 0x81
:device(debug): Unmapped /dev/input/event20 button 124: 0x82
:device(debug): Unmapped /dev/input/event20 button 125: 0x83
:device(debug): Unmapped /dev/input/event20 button 126: 0x84
:device(debug): Unmapped /dev/input/event20 button 127: 0x85
:device(debug): Unmapped /dev/input/event20 button 128: 0x86
:device(debug): Unmapped /dev/input/event20 button 129: 0x87
:device(debug): Unmapped /dev/input/event20 button 130: 0x88
:device(debug): Unmapped /dev/input/event20 button 131: 0x89
:device(debug): Unmapped /dev/input/event20 button 132: 0x8a
:device(debug): Unmapped /dev/input/event20 button 133: 0x8c
:device(debug): Unmapped /dev/input/event20 button 134: 0x8e
:device(debug): Unmapped /dev/input/event20 button 135: 0x96
:device(debug): Unmapped /dev/input/event20 button 136: 0x98
:device(debug): Unmapped /dev/input/event20 button 138: 0x9f
:device(debug): Unmapped /dev/input/event20 button 139: 0xa1
:device(debug): Unmapped /dev/input/event20 button 140: 0xa3
:device(debug): Unmapped /dev/input/event20 button 141: 0xa4
:device(debug): Unmapped /dev/input/event20 button 142: 0xa5
:device(debug): Unmapped /dev/input/event20 button 143: 0xa6
:device(debug): Unmapped /dev/input/event20 button 144: 0xad
:device(debug): Unmapped /dev/input/event20 button 145: 0xb0
:device(debug): Unmapped /dev/input/event20 button 146: 0xb1
:device(debug): Unmapped /dev/input/event20 button 147: 0xb2
:device(debug): Unmapped /dev/input/event20 button 148: 0xb3
:device(debug): Unmapped /dev/input/event20 button 149: 0xb4
:device(debug): Unmapped /dev/input/event20 button 150: 0xb7
:device(debug): Unmapped /dev/input/event20 button 151: 0xb8
:device(debug): Unmapped /dev/input/event20 button 152: 0xb9
:device(debug): Unmapped /dev/input/event20 button 153: 0xba
:device(debug): Unmapped /dev/input/event20 button 154: 0xbb
:device(debug): Unmapped /dev/input/event20 button 155: 0xbc
:device(debug): Unmapped /dev/input/event20 button 156: 0xbd
:device(debug): Unmapped /dev/input/event20 button 157: 0xbe
:device(debug): Unmapped /dev/input/event20 button 158: 0xbf
:device(debug): Unmapped /dev/input/event20 button 159: 0xc0
:device(debug): Unmapped /dev/input/event20 button 160: 0xc1
:device(debug): Unmapped /dev/input/event20 button 161: 0xc2
:device(debug): Unmapped /dev/input/event20 button 162: 0xf0
:device(debug): Unmapped /dev/input/event20 button 168: 0x115
:device(debug): Unmapped /dev/input/event20 button 169: 0x116
:device(debug): Unmapped /dev/input/event20 button 170: 0x117
:device(debug): Unmapped /dev/input/event20 button 171: 0x118
:device(debug): Unmapped /dev/input/event20 button 172: 0x119
:device(debug): Unmapped /dev/input/event20 button 173: 0x11a
:device(debug): Unmapped /dev/input/event20 button 174: 0x11b
:device(debug): Unmapped /dev/input/event20 button 175: 0x11c
:device(debug): Unmapped /dev/input/event20 button 176: 0x11d
:device(debug): Unmapped /dev/input/event20 button 177: 0x11e
:device(debug): Unmapped /dev/input/event20 button 178: 0x11f
:device(debug): Discovered evdev input device Logitech G Pro (connected), 179 buttons, pointer, keyboard
:device(debug): Unmapped /dev/input/event21 button 83: 0x55
:device(debug): Unmapped /dev/input/event21 button 84: 0x56
:device(debug): Unmapped /dev/input/event21 button 87: 0x59
:device(debug): Unmapped /dev/input/event21 button 88: 0x5a
:device(debug): Unmapped /dev/input/event21 button 89: 0x5b
:device(debug): Unmapped /dev/input/event21 button 90: 0x5c
:device(debug): Unmapped /dev/input/event21 button 91: 0x5d
:device(debug): Unmapped /dev/input/event21 button 92: 0x5e
:device(debug): Unmapped /dev/input/event21 button 93: 0x5f
:device(debug): Unmapped /dev/input/event21 button 109: 0x71
:device(debug): Unmapped /dev/input/event21 button 110: 0x72
:device(debug): Unmapped /dev/input/event21 button 111: 0x73
:device(debug): Unmapped /dev/input/event21 button 112: 0x74
:device(debug): Unmapped /dev/input/event21 button 113: 0x75
:device(debug): Unmapped /dev/input/event21 button 115: 0x79
:device(debug): Unmapped /dev/input/event21 button 116: 0x7a
:device(debug): Unmapped /dev/input/event21 button 117: 0x7b
:device(debug): Unmapped /dev/input/event21 button 118: 0x7c
:device(debug): Unmapped /dev/input/event21 button 122: 0x80
:device(debug): Unmapped /dev/input/event21 button 123: 0x81
:device(debug): Unmapped /dev/input/event21 button 124: 0x82
:device(debug): Unmapped /dev/input/event21 button 125: 0x83
:device(debug): Unmapped /dev/input/event21 button 126: 0x84
:device(debug): Unmapped /dev/input/event21 button 127: 0x85
:device(debug): Unmapped /dev/input/event21 button 128: 0x86
:device(debug): Unmapped /dev/input/event21 button 129: 0x87
:device(debug): Unmapped /dev/input/event21 button 130: 0x88
:device(debug): Unmapped /dev/input/event21 button 131: 0x89
:device(debug): Unmapped /dev/input/event21 button 132: 0x8a
:device(debug): Unmapped /dev/input/event21 button 133: 0x8c
:device(debug): Unmapped /dev/input/event21 button 134: 0x8e
:device(debug): Unmapped /dev/input/event21 button 135: 0x96
:device(debug): Unmapped /dev/input/event21 button 136: 0x98
:device(debug): Unmapped /dev/input/event21 button 138: 0x9f
:device(debug): Unmapped /dev/input/event21 button 139: 0xa1
:device(debug): Unmapped /dev/input/event21 button 140: 0xa3
:device(debug): Unmapped /dev/input/event21 button 141: 0xa4
:device(debug): Unmapped /dev/input/event21 button 142: 0xa5
:device(debug): Unmapped /dev/input/event21 button 143: 0xa6
:device(debug): Unmapped /dev/input/event21 button 144: 0xad
:device(debug): Unmapped /dev/input/event21 button 145: 0xb0
:device(debug): Unmapped /dev/input/event21 button 146: 0xb1
:device(debug): Unmapped /dev/input/event21 button 147: 0xb2
:device(debug): Unmapped /dev/input/event21 button 148: 0xb3
:device(debug): Unmapped /dev/input/event21 button 149: 0xb4
:device(debug): Unmapped /dev/input/event21 button 150: 0xb7
:device(debug): Unmapped /dev/input/event21 button 151: 0xb8
:device(debug): Unmapped /dev/input/event21 button 152: 0xb9
:device(debug): Unmapped /dev/input/event21 button 153: 0xba
:device(debug): Unmapped /dev/input/event21 button 154: 0xbb
:device(debug): Unmapped /dev/input/event21 button 155: 0xbc
:device(debug): Unmapped /dev/input/event21 button 156: 0xbd
:device(debug): Unmapped /dev/input/event21 button 157: 0xbe
:device(debug): Unmapped /dev/input/event21 button 158: 0xbf
:device(debug): Unmapped /dev/input/event21 button 159: 0xc0
:device(debug): Unmapped /dev/input/event21 button 160: 0xc1
:device(debug): Unmapped /dev/input/event21 button 161: 0xc2
:device(debug): Unmapped /dev/input/event21 button 162: 0xf0
:device(debug): Discovered evdev input device Logitech Candy (connected), 163 buttons, keyboard
:device(spam): Changed axis 0 (left_x) to 0.0603799 (raw value 1978)
:device(spam): Changed axis 1 (left_y) to 0.0466773 (raw value -1530)
:device(spam): Changed axis 3 (right_x) to 0.000198367 (raw value 6)
:device(spam): Changed axis 4 (right_y) to -0.0295567 (raw value 968)
:device(debug): Discovered evdev input device Xbox 360 Wireless Receiver for Windows (connected), gamepad, 15 buttons, 8 axes, vibration
Verbose mode true.  quiet list = ['NewFrame', 'avatarMoving', 'event-loop-done', 'collisionLoopFinished']
:Messenger(debug): sent event: resetClock sentArgs = [-0.018251000000000017], taskChain = None
:device(spam): Changed axis 0 (left_x) to 0.0604715 (raw value 1981)
:device(spam): Changed axis 3 (right_x) to 0.000289921 (raw value 9)
:device(spam): Changed axis 0 (left_x) to 0.0605325 (raw value 1983)
:device(spam): Changed axis 1 (left_y) to 0.0465553 (raw value -1526)
:device(spam): Changed axis 3 (right_x) to 0.000350958 (raw value 11)
:Messenger(debug): sent event: TaskManager-addTask sentArgs = [PythonTask resetPrevTransform], taskChain = None
:Messenger(debug): sent event: TaskManager-addTask sentArgs = [PythonTask dataLoop], taskChain = None
:Messenger(debug): sent event: TaskManager-addTask sentArgs = [PythonTask ivalLoop], taskChain = None
:Messenger(debug): sent event: TaskManager-addTask sentArgs = [PythonTask collisionLoop], taskChain = None
:Messenger(debug): sent event: TaskManager-addTask sentArgs = [PythonTask garbageCollectStates], taskChain = None
:Messenger(debug): sent event: TaskManager-addTask sentArgs = [PythonTask igLoop], taskChain = None
:Messenger(debug): sent event: TaskManager-addTask sentArgs = [PythonTask audioLoop], taskChain = None
:Messenger(debug): sent event: TaskManager-addTask sentArgs = [PythonTask eventManager], taskChain = None
:device(spam): Changed axis 0 (left_x) to 0.060441 (raw value 1980)
:device(spam): Changed axis 1 (left_y) to 0.0464637 (raw value -1523)
:device(spam): Changed axis 3 (right_x) to 0.000808728 (raw value 26)
:Messenger(debug): sent event: window-event sentArgs = [<panda3d.core.GraphicsWindow object at 0x7f3f0cbc1060>], taskChain = None
:Messenger(debug): sent event: aspectRatioChanged sentArgs = [], taskChain = None
:device(spam): Changed axis 0 (left_x) to 0.0605325 (raw value 1983)
:device(spam): Changed axis 3 (right_x) to 0.00187686 (raw value 61)
:device(spam): Changed axis 4 (right_y) to -0.0299535 (raw value 981)
:device(spam): Changed axis 0 (left_x) to 0.0605936 (raw value 1985)
:device(spam): Changed axis 3 (right_x) to 0.00218204 (raw value 71)
:device(spam): Changed axis 4 (right_y) to -0.0309911 (raw value 1015)
:device(spam): Changed axis 0 (left_x) to 0.0604715 (raw value 1981)
:device(spam): Changed axis 1 (left_y) to 0.0465553 (raw value -1526)
:device(spam): Changed axis 3 (right_x) to 0.00224308 (raw value 73)
:device(spam): Changed axis 4 (right_y) to -0.0306554 (raw value 1004)
:device(spam): Changed axis 0 (left_x) to 0.0603799 (raw value 1978)
:device(spam): Changed axis 1 (left_y) to 0.0466163 (raw value -1528)
:device(spam): Changed axis 3 (right_x) to 0.00215152 (raw value 70)
:device(spam): Changed axis 4 (right_y) to -0.0305638 (raw value 1001)
:device(spam): Changed axis 1 (left_y) to 0.0465248 (raw value -1525)
:device(spam): Changed axis 3 (right_x) to 0.00224308 (raw value 73)
:device(spam): Changed axis 1 (left_y) to 0.0466163 (raw value -1528)
:device(spam): Changed axis 3 (right_x) to 0.00267033 (raw value 87)
:device(spam): Changed axis 1 (left_y) to 0.0466773 (raw value -1530)
:device(spam): Changed axis 3 (right_x) to 0.00276188 (raw value 90)
:device(spam): Changed axis 4 (right_y) to -0.0301366 (raw value 987)
:device(spam): Changed axis 3 (right_x) to 0.00270085 (raw value 88)
:device(spam): Changed axis 4 (right_y) to -0.0290684 (raw value 952)
:device(spam): Changed axis 1 (left_y) to 0.0465553 (raw value -1526)
:device(spam): Changed axis 3 (right_x) to 0.0027924 (raw value 91)
:device(spam): Changed axis 4 (right_y) to -0.0294041 (raw value 963)
:device(spam): Changed axis 1 (left_y) to 0.0466163 (raw value -1528)
:device(spam): Changed axis 3 (right_x) to 0.00285344 (raw value 93)
:device(spam): Changed axis 4 (right_y) to -0.0294652 (raw value 965)
:device(spam): Changed axis 1 (left_y) to 0.0466773 (raw value -1530)
:device(spam): Changed axis 3 (right_x) to 0.00276188 (raw value 90)
:device(spam): Changed axis 4 (right_y) to -0.0295262 (raw value 967)
Assertion failed: code >= 0 && (size_t)code < _button_indices.size() at line 817 of panda/src/device/evdevInputDevice.cxx
:device(spam): Changed button 13 (dpad_up) to down
:device(spam): Changed axis 7 to -1 (raw value -1)
:device(spam): Changed axis 0 (left_x) to 0.0599527 (raw value 1964)
:device(spam): Changed axis 1 (left_y) to 0.0471046 (raw value -1544)
:device(spam): Changed axis 3 (right_x) to 0.00270085 (raw value 88)
:device(spam): Changed axis 4 (right_y) to -0.0299229 (raw value 980)
Traceback (most recent call last):
  File "/home/will/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 2091, in __dataLoop
    self.dgTrav.traverse(self.dataRootNode)
AssertionError: code >= 0 && (size_t)code < _button_indices.size() at line 817 of panda/src/device/evdevInputDevice.cxx
:task(error): Exception occurred in PythonTask dataLoop
Traceback (most recent call last):
  File "/home/will/Sync/projects/panda/bug_test/dpad_crash.py", line 21, in <module>
    app.run()
  File "/home/will/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 3319, in run
    self.taskMgr.run()
  File "/home/will/.local/lib/python3.8/site-packages/direct/task/Task.py", line 541, in run
    self.step()
  File "/home/will/.local/lib/python3.8/site-packages/direct/task/Task.py", line 495, in step
    self.mgr.poll()
  File "/home/will/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 2091, in __dataLoop
    self.dgTrav.traverse(self.dataRootNode)
AssertionError: code >= 0 && (size_t)code < _button_indices.size() at line 817 of panda/src/device/evdevInputDevice.cxx
:Messenger(debug): <__main__.MyApp object at 0x7f3f161aa190> (('MyApp', 1))
 now ignoring all events
:Messenger(debug): <direct.showbase.Loader.Loader object at 0x7f3f10b84f70> (('Loader', 0))
 now ignoring: 'async_loader_0'
[Finished in 2.0s with exit code 1]
[cmd: ['python', '-u', '/home/will/Sync/projects/panda/bug_test/dpad_crash.py']]
```

**Comment by rdb** [comment]
It looks like either a driver bug or Linux kernel bug: your gamepad is sending EV_KEY inputs that aren't reported as supported by the device.

It should be easy to work around this.
