### ISSUE TITLE
build_apps could not find dependencies referenced by

### ISSUE THREAD

**Issue by kergalym** [panda3d/panda3d#1081]
## Description
When building my application I noticed couple mesages:
```
warning: build_apps: could not find dependency libpython3.7m.so.1.0 (referenced by deploy-stub) 
 
warning: build_apps: could not find dependency libssl.so.1.1 (referenced by libp3dtoolconfig.so.1.11) 
 
warning: build_apps: could not find dependency libcrypto.so.1.1 (referenced by libp3dtoolconfig.so.1.11) 
 
warning: build_apps: could not find dependency libfftw3.so.3 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libfreetype.so.6 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libharfbuzz.so.0 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libtiff.so.5 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libIlmImf-2_5.so.25 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libImath-2_5.so.25 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libHalf-2_5.so.25 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libIex-2_5.so.25 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libIexMath-2_5.so.25 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libIlmThread-2_5.so.25 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libvorbisfile.so.3 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libopusfile.so.0 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libjpeg.so.62 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libpng16.so.16 (referenced by libpanda.so.1.11) 
 
warning: build_apps: could not find dependency libavformat.so.58 (referenced by libp3ffmpeg.so) 
 
warning: build_apps: could not find dependency libavcodec.so.58 (referenced by libp3ffmpeg.so) 
 
warning: build_apps: could not find dependency libavutil.so.56 (referenced by libp3ffmpeg.so) 
 
warning: build_apps: could not find dependency libswscale.so.5 (referenced by libp3ffmpeg.so) 
 
warning: build_apps: could not find dependency libswresample.so.3 (referenced by libp3ffmpeg.so) 
 
warning: build_apps: could not find dependency libopenal.so.1 (referenced by libp3openal_audio.so) 
 
warning: build_apps: could not find dependency libffi.so.7 (referenced by _ctypes.so) 
 
warning: build_apps: could not find dependency libBLT24.so (referenced by _tkinter.so) 
 
warning: build_apps: could not find dependency libtk8.6.so (referenced by _tkinter.so) 
 
warning: build_apps: could not find dependency libtcl8.6.so (referenced by _tkinter.so)
```
But these files located like here:
```
$equery b libopenal.so.1
 * Searching for libopenal.so.1 ... 
media-libs/openal-1.20.1 (/usr/lib64/libopenal.so.1 -> libopenal.so.1.20.1)
media-libs/openal-1.20.1 (/usr/lib/libopenal.so.1 -> libopenal.so.1.20.1) 
... 

I run it like 
`python3 setup.py build_apps bdist_apps
`
My built app crashes. I think, due to these missed libs
```
$./testapp
[>] CORE                      Using panda3d-supplied core module 
Known pipe types:
(all display modules loaded.)
Traceback (most recent call last):
  File "__main__", line 1130, in <module>
  File "__main__", line 151, in __init__
  File "direct.showbase.ShowBase", line 289, in __init__
  File "direct.showbase.ShowBase", line 959, in openDefaultWindow
  File "direct.showbase.ShowBase", line 995, in openMainWindow
  File "direct.showbase.ShowBase", line 707, in openWindow
  File "direct.showbase.ShowBase", line 693, in <lambda>
  File "direct.showbase.ShowBase", line 759, in _doOpenWindow
  File "direct.showbase.ShowBase", line 598, in makeDefaultPipe
  File "direct.directnotify.Notifier", line 130, in error
Exception: No graphics pipe is available!
Your Config.prc file must name at least one valid panda display
library via load-display or aux-display.
```

I have no idea from where build_apps takes these files.

Environment:
 * Operating system: Gentoo Linux
 * System architecture: amd64
 * Panda3D version: 1.10.7
 * Installation method: wheel
 * Python version 3.7.9

**Comment by rdb** [comment]
What does your setup.py look like?  And your requirements.txt?

**Comment by kergalym** [comment]
setup.py 
```
from setuptools import setup, find_packages

setup(
    name="Korlan",
    version='0.1.1',
    include_package_data=True,
    options={
        'build_apps': {
            'include_patterns': [
                'Assets/**/*',
                'Assets/**/tex/*',
                'Configs/Language/*.json',
                'Configs/Keyboard/*.json',
                'Configs/Mice/*.json',
                'Settings/UI/*.json',
                'Settings/UI/ui_tex/**/*.png',
                'Settings/UI/ui_tex/*.png',
                'Settings/UI/**/*.ttf',
                'Settings/UI/**/*.txt',
                'Settings/Sound/*.ogg',
                'Engine/Render/**/*.png',
                'Engine/Render/**/*.jpg',
                'Engine/Render/data/**/**/**/*',
                'Engine/Render/**/*.yaml',
                'Engine/Render/**/*.flag',
                'Engine/Render/**/**/**/**/*.prc',
                'Engine/Render/**/**/**/**/*.txt',
                'Engine/Render/**/**/**/**/*.yaml',
                'Engine/Render/**/**/**/**/*.bam',
                'Engine/Render/**/**/**/**/*.ttf',
                'Engine/Render/**/**/**/**/*.ies',
                'Engine/Render/**/**/**/**/*.txo',
                'Engine/Render/**/**/**/**/*.txo.*',
                'Engine/Render/**/**/**/**/*.glsl',
                'Engine/Shaders/**/*.frag',
                'Engine/Shaders/**/*.vert',
                'Engine/Shaders/**/*.glsl',
            ],
            # Workaround for
            # AssertionError: macos_main_app must be defined if more than one gui_app is defined
            # since we don't have support for macos
            'macos_main_app': 'Korlan',
            'gui_apps': {
                'Korlan': 'main.py',
            },
            "icons": {
                "Korlan": ["icon-256.png", "icon-128.png", "icon-48.png", "icon-32.png", "icon-16.png"],
            },
            'platforms': [
                'manylinux1_x86_64',
                'win_amd64',
            ],
            'include_modules': {'*': ['Engine.Render.rpcore.native.GPUCommand',
                                      'Engine.Render.rpcore.native.GPUCommandList',
                                      'Engine.Render.rpcore.native.IESDataset',
                                      'Engine.Render.rpcore.native.InternalLightManager',
                                      'Engine.Render.rpcore.native.PointLight',
                                      'Engine.Render.rpcore.native.ShadowManager',
                                      'Engine.Render.rpcore.native.SpotLight',
                                      'Engine.Render.rpcore.native.TagStateManager',
                                      'Engine.Render.rpcore.native.native_',
                                      'Engine.Render.rplibs.yaml.yaml_py3.error',
                                      'cyaml',
                                      'Engine.Render.rplibs.yaml.yaml_py3.dumper',
                                      'Engine.Render.rplibs.yaml.error',
                                      'Engine.Render.rplibs.yaml.yaml_py3.events',
                                      'Engine.Render.rplibs.yaml.yaml_py3.loader',
                                      'Engine.Render.rplibs.yaml.yaml_py3.nodes',
                                      'ordereddict',
                                      'Engine.Render.rpplugins.ao',
                                      'Engine.Render.rpplugins.ao.plugin',
                                      'Engine.Render.rpplugins.bloom',
                                      'Engine.Render.rpplugins.bloom.plugin',
                                      'Engine.Render.rpplugins.clouds',
                                      'Engine.Render.rpplugins.clouds.plugin',
                                      'Engine.Render.rpplugins.color_correction',
                                      'Engine.Render.rpplugins.color_correction.plugin',
                                      'Engine.Render.rpplugins.dof',
                                      'Engine.Render.rpplugins.dof.plugin',
                                      'Engine.Render.rpplugins.env_probes',
                                      'Engine.Render.rpplugins.env_probes.environment_probe',
                                      'Engine.Render.rpplugins.env_probes.plugin',
                                      'Engine.Render.rpplugins.forward_shading',
                                      'Engine.Render.rpplugins.forward_shading.plugin',
                                      'Engine.Render.rpplugins.fxaa',
                                      'Engine.Render.rpplugins.fxaa.plugin',
                                      'Engine.Render.rpplugins.motion_blur',
                                      'Engine.Render.rpplugins.motion_blur.plugin',
                                      'Engine.Render.rpplugins.pssm',
                                      'Engine.Render.rpplugins.pssm.plugin',
                                      'Engine.Render.rpplugins.scattering',
                                      'Engine.Render.rpplugins.scattering.plugin',
                                      'Engine.Render.rpplugins.skin_shading',
                                      'Engine.Render.rpplugins.skin_shading.plugin',
                                      'Engine.Render.rpplugins.sky_ao',
                                      'Engine.Render.rpplugins.sky_ao.plugin',
                                      'Engine.Render.rpplugins.smaa',
                                      'Engine.Render.rpplugins.smaa.plugin',
                                      'Engine.Render.rpplugins.ssr',
                                      'Engine.Render.rpplugins.ssr.plugin',
                                      'Engine.Render.rpplugins.volumetrics',
                                      'Engine.Render.rpplugins.volumetrics.plugin',
                                      'Engine.Render.rpplugins.vxgi',
                                      'Engine.Render.rpplugins.vxgi.plugin',
                                      'thread',
                                      'Engine.Render.rplibs.yaml.yaml_py3.tokens',
                                      'Engine.Render.rplibs.yaml.yaml_py3.load']},
            'plugins': [
                'pandagl',
                'p3openal_audio',
                'p3ffmpeg',
                'p3ptloader',
            ],
        }
    }
)
```
requerements.txt:
```
Pmw
panda3d
xlib
urllib3
setuptools
configparser
```

**Comment by kergalym** [comment]
I found that build_apps  looks at some custom whl package 1.11 located in whl cache directory. Deleting it fixes my issue.
