### ISSUE TITLE
Bam file with convex hull shape can be saved, but not read.

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1251]
## Description
A bam file (at least with a procedural/dynamic mesh) can be saved, but not subsequently loaded, and fails with:
```shell
Assertion failed: _shape == nullptr at line 197 of panda/src/bullet/bulletConvexHullShape.cxx
Assertion failed: !(shape->getShapeType() == CONVEX_HULL_SHAPE_PROXYTYPE && ((btConvexHullShape *)shape)->getNumVertices() == 0) at line 349 of panda/src/bullet/bulletBodyNode.cxx
Traceback (most recent call last):
  File "procedural_shape.py", line 100, in <module>
    loaded = loader.load_model("repro.bam", loader_options)
  File "/tmp/reprovenv/lib/python3.8/site-packages/direct/showbase/Loader.py", line 288, in loadModel
    node = self.loader.loadSync(Filename(modelPath), loaderOptions)
AssertionError: _shape == nullptr at line 197 of panda/src/bullet/bulletConvexHullShape.cxx
```

## Steps to Reproduce
```python
from direct.showbase.Loader import Loader
from panda3d.bullet import BulletGhostNode, BulletConvexHullShape
from panda3d.core import GeomVertexFormat, GeomVertexData
from panda3d.core import Geom, GeomTriangles, GeomVertexWriter
from panda3d.core import  LoaderOptions, NodePath
from panda3d.core import LVector3

def normalized(*args):
    myVec = LVector3(*args)
    myVec.normalize()
    return myVec

# helper function to make a square given the Lower-Left-Hand and
# Upper-Right-Hand corners

def makeSquare(x1, y1, z1, x2, y2, z2):
    format = GeomVertexFormat.getV3n3cpt2()
    vdata = GeomVertexData('square', format, Geom.UHDynamic)

    vertex = GeomVertexWriter(vdata, 'vertex')
    normal = GeomVertexWriter(vdata, 'normal')
    color = GeomVertexWriter(vdata, 'color')
    texcoord = GeomVertexWriter(vdata, 'texcoord')

    # make sure we draw the sqaure in the right plane
    if x1 != x2:
        vertex.addData3(x1, y1, z1)
        vertex.addData3(x2, y1, z1)
        vertex.addData3(x2, y2, z2)
        vertex.addData3(x1, y2, z2)

        normal.addData3(normalized(2 * x1 - 1, 2 * y1 - 1, 2 * z1 - 1))
        normal.addData3(normalized(2 * x2 - 1, 2 * y1 - 1, 2 * z1 - 1))
        normal.addData3(normalized(2 * x2 - 1, 2 * y2 - 1, 2 * z2 - 1))
        normal.addData3(normalized(2 * x1 - 1, 2 * y2 - 1, 2 * z2 - 1))

    else:
        vertex.addData3(x1, y1, z1)
        vertex.addData3(x2, y2, z1)
        vertex.addData3(x2, y2, z2)
        vertex.addData3(x1, y1, z2)

        normal.addData3(normalized(2 * x1 - 1, 2 * y1 - 1, 2 * z1 - 1))
        normal.addData3(normalized(2 * x2 - 1, 2 * y2 - 1, 2 * z1 - 1))
        normal.addData3(normalized(2 * x2 - 1, 2 * y2 - 1, 2 * z2 - 1))
        normal.addData3(normalized(2 * x1 - 1, 2 * y1 - 1, 2 * z2 - 1))

    # adding different colors to the vertex for visibility
    color.addData4f(1.0, 0.0, 0.0, 1.0)
    color.addData4f(0.0, 1.0, 0.0, 1.0)
    color.addData4f(0.0, 0.0, 1.0, 1.0)
    color.addData4f(1.0, 0.0, 1.0, 1.0)

    texcoord.addData2f(0.0, 1.0)
    texcoord.addData2f(0.0, 0.0)
    texcoord.addData2f(1.0, 0.0)
    texcoord.addData2f(1.0, 1.0)

    # Quads aren't directly supported by the Geom interface
    # you might be interested in the CardMaker class if you are
    # interested in rectangle though
    tris = GeomTriangles(Geom.UHDynamic)
    tris.addVertices(0, 1, 3)
    tris.addVertices(1, 2, 3)

    square = Geom(vdata)
    square.addPrimitive(tris)
    return square

bullet_shape = BulletConvexHullShape()
bullet_shape.add_geom(makeSquare(-1, -1, -1, 1, -1, 1))
bullet_shape.add_geom(makeSquare(-1, 1, -1, 1, 1, 1))
bullet_shape.add_geom(makeSquare(-1, 1, 1, 1, -1, 1))
bullet_shape.add_geom(makeSquare(-1, 1, -1, 1, -1, -1))
bullet_shape.add_geom(makeSquare(-1, -1, -1, -1, 1, 1))
bullet_shape.add_geom(makeSquare(1, -1, -1, 1, 1, 1))
bullet_node = BulletGhostNode()
bullet_node.add_shape(bullet_shape)
np = NodePath(bullet_node)
np.ls()

loader = Loader(base=None)
# Explicitly disable cache - files will only be opened once, and we need to convert the "real" version
loader_options = LoaderOptions(LoaderOptions.LF_no_cache | LoaderOptions.LF_report_errors)
if not loader.save_model("repro.bam", np):
    print("save failed")

loaded = loader.load_model("repro.bam", loader_options)
loaded.ls()
```
(the procedural cube code was pulled from the samples

## Environment
 * Operating system: Ubuntu 20.04 (docker image)
 * System architecture: x86_64
 * Panda3D version: 1.10.11
 * Installation method: pip wheel
 * Python version (if using Python): 3.8.10

**Comment by Clockwork-Muse** [comment]
@Moguri - Has implications for blend2bam, especially if the shape is a piece of invisible geometry. 

Bizarrely, on my real model, that I'm running exporting via a custom script (calling procedures inside of blend2bam to get glbs out for the real pipeline), it's triangle mesh shapes that are segfaulting, but a convex hull works fine... I haven't gotten a repro on the triangle shape yet, though, so I'm not sure what's really going on.

**Comment by Clockwork-Muse** [comment]
From the look of things, actually initializing by calling the constructor in `make_from_bam()`, instead of letting it be default initialized.

**Comment by Clockwork-Muse** [comment]
Working on a fix now for convex now - should be just initializing the two variables.

**Comment by Clockwork-Muse** [comment]
Side note: I can no longer get this to repro on custom built images, even if I'm building same commit as in the official wheel - I'm not sure why.

**Comment by Clockwork-Muse** [comment]
Correction - I misread the assertion;

`BulletConvexHullShape`, unlike most (all?) of the other shapes, initializes the wrapped bullet shape as part of the default constructor.  Flipping the assert fixes the issue.

There's a couple of other oddities with it, though.
Currently, `add_point` adds the point to the existing shape, but `add_geom` and `add_array` both create a new shape.  Meaning if you want to get a convex box around multiple geoms... you can't.

@rdb thoughts?
