### ISSUE TITLE
gl-version 3 2 conflict with the light

### ISSUE THREAD

**Issue by springertang** [panda3d/panda3d#1283]
## Description

When I use the gl-version 3 2 configVars, all the light effect including DirectionalLight, PointLight, AmbientLight...etc not working.

## Steps to Reproduce

1. Try to add some light effect on the Panda3D.
Panda3D Lighting : https://docs.panda3d.org/1.10/python/programming/render-attributes/lighting

2. Then run the program. It should be some light in the environment.

3. Add those codes in the beginning:
```
configVars = """
gl-version 3 2
"""
loadPrcFileData("", configVars)
```
4. Run the program again. The light effect will dismiss.

## Environment
 * Operating system: macbook2019 Monterey
 * System architecture: Apple–Intel architecture
 * Panda3D version: Panda3D 1.10.11
 * Installation method: (eg. pip, wheel, SDK, built from source) pip install panda3d==1.10.11
 * Python version (if using Python): Python 3.10.0
 * Compiler (if using C++):

**Comment by Moguri** [comment]
The fixed-function pipeline is not supported when using `gl-version 3 2` so make sure you either:

* enable the auto shader
* use pre-built shaders (e.g., simplepbr)
* write custom shaders

**Comment by springertang** [comment]
@Moguri 
I try the `auto shader` and `simplepbr`. But not working, Here is my code:
```
import simplepbr
from panda3d.core import loadPrcFileData

configVars = """
win-size 1280 720
fullscreen 0
show-frame-rate-meter 1
"""

loadPrcFileData("", configVars)

from direct.showbase.ShowBase import ShowBase
from panda3d.core import PointLight, AmbientLight, NodePath
from math import sin, cos
from direct.filter.CommonFilters import CommonFilters


class LightsAndShadows(ShowBase):
    def __init__(self):
        super().__init__()
        self.set_background_color(0, 0, 0, 1)
        self.cam.setPos(0, -12, 0)

        # simplepbr
        # simplepbr.init()


        self.tree1 = self.loader.loadModel('jack')
        self.tree1.setPos(0, 0, -2.5)
        self.tree1.reparentTo(self.render)

        self.tree2 = self.loader.loadModel('jack')
        self.tree2.setPos(4, 5, 2.5)
        self.tree2.reparentTo(self.render)

        self.tree3 = self.loader.loadModel('jack')
        self.tree3.setPos(-4, 7, 2.5)
        self.tree3.reparentTo(self.render)

        # self.trees.reparentTo(self.render)

        self.floor = self.loader.loadModel('my-models/floor')
        self.floor.setPos(0, 0, -2.5)
        self.floor.reparentTo(self.render)

        self.light_model = self.loader.loadModel('models/misc/sphere')
        self.light_model.setScale(0.2, 0.2, 0.2)
        # self.light_model.setPos(4, -4, 0)
        self.light_model.reparentTo(self.render)

        plight = PointLight("plight")
        plight.setShadowCaster(True, 1024, 1024)
        self.render.setShaderAuto()
        plnp = self.light_model.attachNewNode(plight)
        # plight.setAttenuation((1, 0, 0)) # constant, linear, and quadratic.
        self.render.setLight(plnp)

        alight = AmbientLight("alight")
        alight.setColor((0.04, 0.04, 0.04, 1))
        alnp = self.render.attachNewNode(alight)
        self.render.setLight(alnp)

        self.floor.setLight(plnp)
        self.floor.setLight(alnp)

        filters = CommonFilters(self.win, self.cam)
        filters.setBloom(size="large")

         # Auto Shader
        # self.render.setShaderAuto()

        self.taskMgr.add(self.move_light, "move-light")

    def move_light(self, task):
        ft = globalClock.getFrameTime()

        self.light_model.setPos(cos(ft)*4, sin(ft)*4, 0)

        return task.cont


game = LightsAndShadows()
game.run()
```
I commented the `self.render.setShaderAuto()` and `simplepbr.init()`. If you want to use it you can uncomment the commands.
1. `self.render.setShaderAuto()` not working in my program.
2. `simplepbr.init()` have those error:
```

Traceback (most recent call last):
  File "/Users//gitdir/fyp/panda3d/other/test_lighting.py", line 81, in <module>
    game = LightsAndShadows()
  File "/Users//gitdir/fyp/panda3d/other/test_lighting.py", line 25, in __init__
    simplepbr.init()
  File "/Users//opt/anaconda3/envs/py310/lib/python3.10/site-packages/simplepbr/__init__.py", line 350, in init
    return Pipeline(**kwargs)
  File "/Users//opt/anaconda3/envs/py310/lib/python3.10/site-packages/simplepbr/__init__.py", line 128, in __init__
    self._recompile_pbr()
  File "/Users//opt/anaconda3/envs/py310/lib/python3.10/site-packages/simplepbr/__init__.py", line 214, in _recompile_pbr
    pbr_vert_str = _load_shader_str('simplepbr.vert', pbr_defines)
  File "/Users//opt/anaconda3/envs/py310/lib/python3.10/site-packages/simplepbr/__init__.py", line 48, in _load_shader_str
    with open(os.path.join(shader_dir, shaderpath)) as shaderfile:
FileNotFoundError: [Errno 2] No such file or directory: './shaders/simplepbr.vert'
```
If you don't understand my explain, please feel free to tell me. And thank you for reading this post.

**Comment by rdb** [comment]
@springertang I believe this should be addressed with the latest version of simplepbr, are you still facing issues?

**Comment by rdb** [comment]
Closing as this is already addressed by other solutions (simplepbr or the new shader pipeline coming in 1.11)
