### ISSUE TITLE
Sysconfigdata is not included in the builds

### ISSUE THREAD

**Issue by cflavio** [panda3d/panda3d#1326]
## Description
I am trying to make a build which uses xmlrpc (but it should happen with every module that needs sysconfigdata). When I launch the build I get:

```
Traceback (most recent call last):
  File "__main__", line 2, in <module>
  File "importlib._bootstrap", line 1027, in _find_and_load
  File "importlib._bootstrap", line 1006, in _find_and_load_unlocked
  File "importlib._bootstrap", line 688, in _load_unlocked
  File "importlib._bootstrap", line 856, in exec_module
  File "xmlrpc.server", line 117, in <module>
  File "importlib._bootstrap", line 1027, in _find_and_load
  File "importlib._bootstrap", line 1006, in _find_and_load_unlocked
  File "importlib._bootstrap", line 688, in _load_unlocked
  File "importlib._bootstrap", line 856, in exec_module
  File "pydoc", line 462, in <module>
  File "pydoc", line 492, in Doc
  File "sysconfig", line 572, in get_path
  File "sysconfig", line 562, in get_paths
  File "sysconfig", line 218, in _expand_vars
  File "sysconfig", line 615, in get_config_vars
  File "sysconfig", line 477, in _init_posix
  File "importlib._bootstrap", line 1027, in _find_and_load
  File "importlib._bootstrap", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'
```
## Steps to Reproduce
main.py
```
import direct.directbase.DirectStart
import xmlrpc.server
base.run()
```
setup.py
```from setuptools import setup
setup(
    name='try_xmlrpc',
    options = {
        'build_apps': {
            'gui_apps': {'try_xmlrpc': 'main.py'},
            'log_filename': '$USER_APPDATA/try_xmlrpc/output.log',
            'plugins': ['pandagl', 'p3openal_audio']}})
```
requirements.txt
```
panda3d
```

I create a build with:
```
python setup.py build_apps
```
Then I launch the build in ``build/manylinux2010_x86_64``.
## Environment
 * Operating system: OpenSUSE Tumbleweed
 * System architecture: amd64
 * Panda3D version: 1.10.11
 * Installation method: pip
 * Python version: 3.10.5

**Comment by pmp-p** [comment]
in fact that is pydoc that need sysconfig not xmlrpc

**Comment by el-dee** [comment]
With python < 3.8,  the sysconfigdata module is called `_sysconfigdata_m_linux_x86_64-linux-gnu.py` with the `m` flag. the current code in `FreezeTool.py` is not aware of this fact and so the problem is still present with Python 3.7 (and older)

<pre>
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    'p3openal_audio',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ld/.local/lib/python3.7/site-packages/direct/dist/commands.py", line 550, in run
    self.build_binaries(platform, build_dir, build_dir)
  File "/home/ld/.local/lib/python3.7/site-packages/direct/dist/commands.py", line 1033, in build_binaries
    create_runtime(platform, appname, scriptname, False)
  File "/home/ld/.local/lib/python3.7/site-packages/direct/dist/commands.py", line 958, in create_runtime
    freezer.done(addStartupModules=True)
  File "/home/ld/.local/lib/python3.7/site-packages/direct/dist/FreezeTool.py", line 1197, in done
    self.__loadModule(self.ModuleDef('_sysconfigdata__linux_' + arch + '-linux-gnu', implicit=True))
  File "/home/ld/.local/lib/python3.7/site-packages/direct/dist/FreezeTool.py", line 1287, in __loadModule
    self.mf.import_hook(mdef.moduleName)
  File "/usr/lib/python3.7/modulefinder.py", line 121, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/lib/python3.7/modulefinder.py", line 189, in find_head_package
    raise ImportError("No module named " + qname)
ImportError: No module named _sysconfigdata__linux_x86_64-linux-gnu
</pre>

**Comment by pmp-p** [comment]
also when cross compiling sysconfigdata can be hard to guess if using host python for packaging.
setting _PYTHON_SYSCONFIGDATA_NAME can force a choosen name before importing sysconfig.

**Comment by rdb** [comment]
@el-dee thanks for noticing, I will check in a fix shortly
