### ISSUE TITLE
DirectEntry with both backgroundFocus=1 and overflow=1 leave hanging events after being destroyed, causing a segmentation fault

### ISSUE THREAD

**Issue by Wizzerinus** [panda3d/panda3d#1650]
## Description
Having a `DirectEntry(backgroundFocus=1, overflow=1)` sets up a hanging event on the Entry which triggers on any text input. When the Entry is destroyed, and then any key is pressed, the engine segfaults (specific way depends on the OS; Linux: `python3: built/include/mutexPosixImpl.I:89: ReMutexPosixImpl::~ReMutexPosixImpl(): Assertion 'result == 0' failed.`. Windows: window closes after 2-4 key presses. Mac: untested).

This can be fixed with an `Entry.ignoreAll()`, however due to the obscurity of the bug and difficulty to find it I am reporting it anyway.

## Steps to Reproduce
Create this file:

```python
from direct.gui.DirectEntry import DirectEntry
from direct.showbase.ShowBase import ShowBase


entry = DirectEntry(backgroundFocus=1, overflow=1)
entry.destroy()
ShowBase().run()
```
Then run it and press any key (YMMV since this is slightly harder to trigger on Windows)

Note that both `backgroundFocus` and `overflow` are required

## Environment
 * Operating system: Fedora Linux
 * System architecture: x86_64
 * Panda3D version: 1.11.0
 * Installation method: build from source
 * Python version (if using Python): 3.12
 * Compiler (if using C++): gcc 13.2.1

**Comment by BMaxV** [comment]
I can't reproduce this.

 * OS: Ubuntu 22.04 jammy
 * Kernel: x86_64 Linux 5.15.0-105-generic
 * panda3d.__version__: '1.11.0.dev3233'
 * Python 3.10.12
 * install method pip? but I used the prebuilt one.

**Comment by ArsThaumaturgis** [comment]
Conversely, it reproduces as described on my system.

OS: Ubuntu 22.04.4
Panda version: 1.10.14
Python version: 3.10.12
Install method: Pip, I think.

**Comment by Wizzerinus** [comment]
> This can be fixed with an Entry.ignoreAll(), however due to the obscurity of the bug and difficulty to find it I am reporting it anyway.

I think this is actually wrong, as I'm still getting the crash on the test file with `entry.directAll()` added (not sure why it didn't happen before), Panda3D 1.10.14

**Comment by Wizzerinus** [comment]
The GDB backtrace in case this is of any help:
```
#0  0x00007ffff76ae834 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff765c8ee in raise () from /lib64/libc.so.6
#2  0x00007ffff76448ff in abort () from /lib64/libc.so.6
#3  0x00007ffff764481b in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007ffff7654c57 in __assert_fail () from /lib64/libc.so.6
#5  0x00007fffe7f52791 in ?? () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#6  0x00007fffe83cd0d8 in PGItem::~PGItem() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#7  0x00007fffe83cd579 in PGEntry::~PGEntry() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#8  0x00007fffe7e73ebb in NodePathComponent::~NodePathComponent() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#9  0x00007fffe7f9bcaa in ScissorEffect::~ScissorEffect() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#10 0x00007fffe7f64715 in RenderEffects::~RenderEffects() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#11 0x00007fffe7f64839 in RenderEffects::~RenderEffects() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#12 0x00007fffe7f511d3 in PandaNode::CData::~CData() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#13 0x00007fffe7f513ac in PandaNode::CData::~CData() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#14 0x00007fffe811d516 in PipelineCyclerTrueImpl::~PipelineCyclerTrueImpl() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#15 0x00007fffe7f3062c in PandaNode::~PandaNode() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#16 0x00007fffe7f307e9 in PandaNode::~PandaNode() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#17 0x00007fffe7e73ebb in NodePathComponent::~NodePathComponent() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#18 0x00007fffe7e77cf5 in ?? () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#19 0x00007fffe7ea69fc in NodePath::remove_node(Thread*) () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#20 0x00007fffe83cf026 in PGEntry::update_text() () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#21 0x00007fffe83cfab0 in PGEntry::press(MouseWatcherParameter const&, bool) () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#22 0x00007fffe83c7d00 in PGItem::background_press(MouseWatcherParameter const&) () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#23 0x00007fffe836c777 in MouseWatcher::global_keyboard_press(MouseWatcherParameter const&) ()
   from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
#24 0x00007fffe836c979 in MouseWatcher::press(ButtonHandle, bool) () from /home/wizzerinus/.local/share/virtualenvs/panda3d-latest/lib64/python3.12/site-packages/panda3d/libpanda.so.1.10
```

**Comment by rdb** [comment]
PGEntry is removing itself from the scene graph while the event is being processed, causing a crash. Pushing a fix shortly, which grabs a ref while it's processing the background focus, and also ensures that the iterator isn't invalidated.
