### ISSUE TITLE
Unexplained Panda3D Pipe Errors

### ISSUE THREAD

**Issue by nosyliam** [panda3d/panda3d#201]
I'm unable to work on a Panda3D project because of these random GL/Direct3D errors that came out of nowhere. I was testing out the project with the Panda3D SDK until suddenly I was unable to open the ppython window (I could only see the default windows border for a split-second when I tried to view it) and afterwards I was greeted with startup/init errors. Logs:

```
:Client: Loading Base...
Known pipe types:
  wglGraphicsPipe
(1 aux display modules not yet loaded.)
:ToonBase: Default graphics pipe is wglGraphicsPipe (OpenGL).
:ToonBase: Got aux graphics pipe wdxGraphicsPipe9 (DirectX9).
:ToonBase: Trying pipe type wdxGraphicsPipe9 (DirectX9)
:display:wdxdisplay9(warning): presentation_params->BackBufferWidth : 148
:display:wdxdisplay9(warning): presentation_params->BackBufferHeight : 0
:display:wdxdisplay9(warning): presentation_params->BackBufferFormat : 21
:display:wdxdisplay9(warning): presentation_params->BackBufferCount : 1
:display:wdxdisplay9(warning): D3D CreateDevice failed for adapter #0 at (c:\users\documents\panda\panda\src\dxgsg9\wdxGraphicsWindow9.cxx:754), hr=E_INVALIDARG: An invalid parameter was passed to the returning function
:ToonBase(warning): Unable to open 'onscreen' window.
Traceback (most recent call last):
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "ClientStart.py", line 322, in <module>
    ToonBase.ToonBase()
  File "ToonBase.py", line 41, in __init__
    OTPBase.OTPBase.__init__(self)
  File "OTPBase.py", line 16, in __init__
    ShowBase.__init__(self, windowType = windowType)
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 285, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 934, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "ToonBase.py", line 381, in openMainWindow
    result = OTPBase.OTPBase.openMainWindow(self, *args, **kw)
  File "OTPBase.py", line 227, in openMainWindow
    result = ShowBase.openMainWindow(self, *args, **kw)
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 970, in openMainWindow
    self.openWindow(*args, **kw)
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 719, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.
```

To make it even stranger, I'm able to run the game completely fine on an embedded Panda3D client. I've already updated my PC, installed the latest NVIDIA graphics drivers for my card, and uninstalled and reinstalled Panda3D. Any insights to what's going on would be greatly appreciated!

**Comment by rdb** [comment]
Are you able to run pview.exe at all?  If not, could you please set "notify-level-display spam" and "notify-level-glgsg spam", redirect the output to a file and post it here?

**Comment by nosyliam** [comment]
Somehow, deleting my game's source and re-cloning it fixed the issue. Guess it was just one of those random, unexplained flukes so I'll close the issue.
