### ISSUE TITLE
deploy-ng's issue with include_modules

### ISSUE THREAD

**Issue by cflavio** [panda3d/panda3d#242]
In a system with the package _keyring_ installed:
`pip install keyring`

If I create a simple file _main.py_:
`print 'hello world'`

With the following _setup.py_:
```
from setuptools import setup

setup(
    name='example',
    options = {
        'build_apps': {
            'gui_apps': {'example': 'main.py'},
            'platforms': ['manylinux1_x86_64'],
            'include_modules': {'*': ['keyring.backends.*']}
        }
    }
)
```

With the following _requirements.txt_:
```
--pre --extra-index-url https://archive.panda3d.org/branches/deploy-ng
panda3d
```

When I run deploy-ng:
`$ python setup.py bdist_apps`

I get the following error:
```
running bdist_apps
running build_apps
Building platforms: manylinux1_x86_64
Gathering wheels for platform: manylinux1_x86_64
Collecting panda3d (from -r ./requirements.txt (line 2))
  File was already downloaded /home/flavio/Desktop/asteroids/build/__whl_cache__/panda3d-1.10.0.dev1282+deployng.170-cp27-cp27mu-manylinux1_x86_64.whl
Successfully downloaded panda3d
Building runtime for platform: manylinux1_x86_64
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    'include_modules': {'*': ['keyring.backends.*']}
  File "/home/flavio/Desktop/asteroids/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/flavio/Desktop/asteroids/venv/local/lib/python2.7/site-packages/direct/showutil/dist.py", line 769, in run
    self.run_command('build_apps')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/flavio/Desktop/asteroids/venv/local/lib/python2.7/site-packages/direct/showutil/dist.py", line 152, in run
    self.build_runtimes(platform, use_wheels)
  File "/home/flavio/Desktop/asteroids/venv/local/lib/python2.7/site-packages/direct/showutil/dist.py", line 325, in build_runtimes
    create_runtime(appname, scriptname, False)
  File "/home/flavio/Desktop/asteroids/venv/local/lib/python2.7/site-packages/direct/showutil/dist.py", line 282, in create_runtime
    freezer.done(addStartupModules=True)
  File "/home/flavio/Desktop/asteroids/venv/local/lib/python2.7/site-packages/direct/showutil/FreezeTool.py", line 1072, in done
    self.__loadModule(self.ModuleDef(modname, implicit = True))
  File "/home/flavio/Desktop/asteroids/venv/local/lib/python2.7/site-packages/direct/showutil/FreezeTool.py", line 1158, in __loadModule
    self.mf.import_hook(mdef.moduleName)
  File "/usr/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/lib/python2.7/modulefinder.py", line 226, in load_tail
    raise ImportError, "No module named " + mname
ImportError: No module named pkg_resources.*
```

**Comment by Moguri** [comment]
Are you still running into this issue after updating your build environment?

**Comment by cflavio** [comment]
Yes, I do.

**Comment by Moguri** [comment]
@cflavio Can you test if 0c3c6c36bfd8dbf80e70a1f3276b276d7575cd83 fixes the problem for you?

**Comment by rdb** [comment]
I just checked in a fix for that error, can you try again?

**Comment by cflavio** [comment]
Sure! This is the new result:

```
$ python setup.py bdist_apps
running bdist_apps
running build_apps
Building platforms: manylinux1_x86_64
Gathering wheels for platform: manylinux1_x86_64
Collecting panda3d (from -r ./requirements.txt (line 2))
  Downloading http://buildbot.panda3d.org/downloads/15dd70f25442a380900d2b418f95365433b23d14/panda3d-1.10.0.dev1282+deployng.174-cp27-cp27mu-manylinux1_x86_64.whl (47.5MB)
    100% |████████████████████████████████| 47.6MB 1.6MB/s 
  Saved ./build/__whl_cache__/panda3d-1.10.0.dev1282+deployng.174-cp27-cp27mu-manylinux1_x86_64.whl
Successfully downloaded panda3d
Building runtime for platform: manylinux1_x86_64
('pkg_resources', 'pkg_resources.*.*')
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    'include_modules': {'*': ['keyring.backends.*']}
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/dist.py", line 769, in run
    self.run_command('build_apps')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/dist.py", line 152, in run
    self.build_runtimes(platform, use_wheels)
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/dist.py", line 325, in build_runtimes
    create_runtime(appname, scriptname, False)
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/dist.py", line 282, in create_runtime
    freezer.done(addStartupModules=True)
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/FreezeTool.py", line 1087, in done
    self.__loadModule(mdef)
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/FreezeTool.py", line 1180, in __loadModule
    self.mf.import_hook(mdef.moduleName)
  File "/usr/lib/python2.7/modulefinder.py", line 146, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/lib/python2.7/modulefinder.py", line 223, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/FreezeTool.py", line 2230, in load_module
    return modulefinder.ModuleFinder.load_module(self, fqname, fp, pathname, file_info)
  File "/usr/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/lib/python2.7/modulefinder.py", line 208, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/FreezeTool.py", line 2230, in load_module
    return modulefinder.ModuleFinder.load_module(self, fqname, fp, pathname, file_info)
  File "/usr/lib/python2.7/modulefinder.py", line 324, in load_module
    self.scan_code(co, m)
  File "/usr/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/lib/python2.7/modulefinder.py", line 453, in scan_code
    self.scan_code(c, m)
  File "/usr/lib/python2.7/modulefinder.py", line 420, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/lib/python2.7/modulefinder.py", line 342, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/lib/python2.7/modulefinder.py", line 145, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/lib/python2.7/modulefinder.py", line 201, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/lib/python2.7/modulefinder.py", line 293, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/home/flavio/Desktop/moguri/venv/local/lib/python2.7/site-packages/direct/showutil/FreezeTool.py", line 2230, in load_module
    return modulefinder.ModuleFinder.load_module(self, fqname, fp, pathname, file_info)
  File "/usr/lib/python2.7/modulefinder.py", line 309, in load_module
    co = compile(fp.read()+'\n', pathname, 'exec')
  File "/home/flavio/Desktop/moguri/venv/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 1311: invalid continuation byte
```

**Comment by Moguri** [comment]
@cflavio I setup a Python 2 environment and got your example working with 5b4041bf234dc3f9b2b2cc799cceb088f3668881. Can you see if this fixes the issue for you as well?

**Comment by cflavio** [comment]
It works! Thank you very much!
