### ISSUE TITLE
deploy_ng has problems with non-ascii characters

### ISSUE THREAD

**Issue by wezu** [panda3d/panda3d#243]
When building an app on Windows 10 with deploy_ng I got some errors when the source files where encoded using utf-8 with bom:
```Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    'win32'
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\dist.py", line 792, in se
tup
    distutils.core.setup(**attrs)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\dist.py", line 152, in ru
n
    self.build_runtimes(platform, use_wheels)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\dist.py", line 325, in bu
ild_runtimes
    create_runtime(appname, scriptname, False)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\dist.py", line 282, in cr
eate_runtime
    freezer.done(addStartupModules=True)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\FreezeTool.py", line 1049
, in done
    self.__loadModule(mdef)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\FreezeTool.py", line 1151
, in __loadModule
    self.mf.load_module(mdef.moduleName, fp, pathname, stuff)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\modulefinder.py", line 288, in load_module
    co = compile(fp.read()+'\n', pathname, 'exec')
  File "main.py", line 1
    ï»¿from panda3d.core import *
          ^
SyntaxError: invalid character in identifier
```

But it also has problems with non-ascii characters in the script (in this case: ↑↓ →←)
```Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    'win32'
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\dist.py", line 792, in se
tup
    distutils.core.setup(**attrs)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\dist.py", line 152, in ru
n
    self.build_runtimes(platform, use_wheels)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\dist.py", line 325, in bu
ild_runtimes
    create_runtime(appname, scriptname, False)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\dist.py", line 282, in cr
eate_runtime
    freezer.done(addStartupModules=True)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\FreezeTool.py", line 1049
, in done
    self.__loadModule(mdef)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\site-packages\direct\showutil\FreezeTool.py", line 1151
, in __loadModule
    self.mf.load_module(mdef.moduleName, fp, pathname, stuff)
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\modulefinder.py", line 288, in load_module
    co = compile(fp.read()+'\n', pathname, 'exec')
  File "C:\Users\wezu\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 415: character maps to <undefined>
```
The included zip has both the problems utf-8 with bom source code and non-ascii characters (I also had to pack a font file in because the default font has no definitions for these characters)

[non_ascii.zip](https://github.com/panda3d/panda3d/files/1710798/non_ascii.zip)
The problematic code  is as simple as it gets:
```python
from panda3d.core import *
from direct.showbase import ShowBase
from direct.gui.DirectGui import *

class Demo():
    def __init__(self):
        base = ShowBase.ShowBase()

        font = loader.loadFont('PressStart2P.ttf')

        self.text_frame=DirectFrame(frameSize=(-640, 0, 0, 480),
                                 frameColor=(1,0,0, 0.0),
                                 text='Some arrows: ↑↓→←',
                                 text_scale=32,
                                 text_font=font,
                                 text_fg=(1,1,1,1),
                                 text_pos=(-320,480-32),
                                 text_align=TextNode.ACenter,
                                 parent=pixel2d)
        self.text_frame.set_pos(640, 0, -480)

d=Demo()
base.run()
```

**Comment by Moguri** [comment]
Does the following command return cp1252 on your system?

`python -c 'import locale; print(locale.getpreferredencoding(False))'`

@rdb We should specify an encoding when opening files that we want to read and dump into compile. Should we always specify utf8 or do we want to get fancier with encoding detection?

**Comment by rdb** [comment]
@Moguri: actually, it seems that Python can figure out the encoding on its own if we pass `compile()` a bytes object instead of a unicode string.  Presumably it will also handle the BOM as well as any `# coding` declaration.  So we should be opening the Python file in binary mode rather than text mode.

I don't quite know how this would work in Python 2 (or whether this is even an issue there).

**Comment by wezu** [comment]
@Moguri: Yes, `locale.getpreferredencoding(False)` returns `cp1252`

**Comment by Moguri** [comment]
@rdb Looks like ModuleFinder calls compile(), but expects a text file-like object since it appends '\n' to fp.read():
`  File "/home/mitchell/panda3d_venv/lib/python3.6/site-packages/direct/showutil/FreezeTool.py", line 1151, in __loadModule
    self.mf.load_module(mdef.moduleName, fp, pathname, stuff)
  File "/usr/lib64/python3.6/modulefinder.py", line 288, in load_module
    co = compile(fp.read()+'\n', pathname, 'exec')
`

**Comment by rdb** [comment]
@Moguri Egad.  Well, we subclass ModuleFinder, and we already override `load_module` with custom behaviour for `imp.FROZEN` modules, so we'll just have to extend that to also handle the `imp.PY_SOURCE` case.

**Comment by Moguri** [comment]
@wezu Can you see if 8f919b7e405e0a880f5af5ee36a3447de552d813 solves this issue for you?

@rdb looks like we override find_module(), not load_module(). I have added a load_module() override and copied the Python 3.6 version over and made the necessary tweaks. This fix only works for Python 3 (I am not sure Python 2 can even support unicode in source files).

**Comment by wezu** [comment]
Just tested with the newest version and the sample worked. I'd say it's solved until proven otherwise.
