### ISSUE TITLE
Issue with Tk when enabling the SceneGraph Browser

### ISSUE THREAD

**Issue by SkyLeach** [panda3d/panda3d#281]
```
| => ./main.py
Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
activate_osx_application
Traceback (most recent call last):
  File "./main.py", line 397, in <module>
    game = SIMGame()
  File "./main.py", line 166, in __init__
    super().__init__()
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 448, in __init__
    self.__doStartDirect()
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 3034, in __doStartDirect
    self.startDirect(fWantDirect = fDirect, fWantTk = fTk, fWantWx = fWx)
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/direct/showbase/ShowBase.py", line 3010, in startDirect
    self.direct = DirectSession.DirectSession()
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/direct/directtools/DirectSession.py", line 297, in __init__
    self.panel = DirectSessionPanel.DirectSessionPanel(parent = tkroot)
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/direct/tkpanels/DirectSessionPanel.py", line 41, in __init__
    AppShell.__init__(self, parent)
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/direct/tkwidgets/AppShell.py", line 100, in __init__
    self.__createInterface()
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/direct/tkwidgets/AppShell.py", line 122, in __createInterface
    self.createInterface()
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/direct/tkpanels/DirectSessionPanel.py", line 184, in createInterface
    notebook = Pmw.NoteBook(notebookFrame)
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/Pmw/Pmw_2_0_1/lib/PmwNoteBook.py", line 60, in __init__
    Pmw.Color.bordercolors(self, self['hull_background'])
  File "/Users/magregor/.virtualenvs/SIM/lib/python3.6/site-packages/Pmw/Pmw_2_0_1/lib/PmwColor.py", line 359, in bordercolors
    '#%04x%04x%04x' % (lightRGB[0], lightRGB[1], lightRGB[2]),
TypeError: %x format: an integer is required, not float
```

**Comment by SkyLeach** [comment]
Looks like this may be a bug in Pmw... checking fix, to be sure.

**Comment by SkyLeach** [comment]
verified as a Pmw bug, closing issue.

**Comment by rdb** [comment]
Looks like a duplicate of #276.  Does the fix introduced in that issue work for you?

**Comment by SkyLeach** [comment]
@rdb I don't think so, no. (but I haven't tried it yet, so I may be wrong?)

The change introduced still uses the old python 2.7 format for FP precision on lines 30 and 31 which was depricated back in 3.2 and enforced as of 3.5.1 IIRC.

Your commit in #276 seems to replicate it?  I don't know how that would work with my python (3.6.4)

**Comment by SkyLeach** [comment]
I updated panda3d and I'm building from master to see if I get the same problem.  In the meantime, here is a quick test:

```
(SIM) ________________________________________________________________________________
| ~/src/SIM/simgame @ MAGREGOR-M-W0XX (magregor)
| => python
Python 3.6.4 (default, Jan  6 2018, 11:51:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> testar = [0.1,0.2,0.3]
>>> print("#%0.2x%0.2x%0.2x" % tuple(f for f in testar))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: %x format: an integer is required, not float
>>>
```
