### ISSUE TITLE
Segmentation fault using python_tags dictionary syntax

### ISSUE THREAD

**Issue by Negdayen** [panda3d/panda3d#326]
```
(localenv) fuzzybunny@xubuntu:~$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from panda3d.core import NodePath
>>> n = NodePath("n")
>>> n.python_tags["foo"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'foo'
>>> n.python_tags["foo"] = "bar"
Segmentation fault (core dumped)
(localenv) fuzzybunny@xubuntu:~$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from panda3d.core import NodePath
>>> n = NodePath("n")
>>> n.python_tags["food"] = "bar"
>>> n.python_tags["food"] # I must be hungry.
Segmentation fault (core dumped)
(localenv) fuzzybunny@xubuntu:~$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from panda3d.core import NodePath
>>> n = NodePath("n")
>>> n.set_python_tag("foo", "bar")
>>> n.get_python_tag("foo")
'bar'
>>> import panda3d; print(panda3d.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'panda3d' has no attribute '__version__'
>>> from panda3d.core import PandaSystem; print(PandaSystem.getGitCommit())
49dfcb09b9f5dca11c2a64c5858c7bd237bbf1f0
```
Tested under commit 49dfcb09b9f5dca11c2a64c5858c7bd237bbf1f0 and commit 4bac9efffef41be4837435e0f11888a7c84178cd.

**Comment by rdb** [comment]
I think this is fixed now, could you confirm?

**Comment by Negdayen** [comment]
Seems to work great!
