### ISSUE TITLE
Gamepad input samples don't work on Python 2.7

### ISSUE THREAD

**Issue by Sparkpin** [panda3d/panda3d#498]
The gamepad input samples do not appear to work using x64 builds. On Windows, I get the following errors:

gamepad.py

```
C:\Panda3D-1.10.0-x64\samples\gamepad>gamepad.py
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:device(debug): GIDC_ARRIVAL: \\?\HID#VID_045E&PID_028E&IG_00#7&1c345030&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
:device(debug): Initializing XInput library.
:device(debug): Successfully loaded Xinput1_4.dll
Traceback (most recent call last):
  File "C:\Panda3D-1.10.0-x64\direct\showbase\EventManager.py", line 47, in eventLoopTask
    self.doEvents()
  File "C:\Panda3D-1.10.0-x64\direct\showbase\EventManager.py", line 41, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "C:\Panda3D-1.10.0-x64\direct\showbase\EventManager.py", line 98, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.10.0-x64\direct\showbase\Messenger.py", line 333, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.10.0-x64\direct\showbase\Messenger.py", line 418, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Panda3D-1.10.0-x64\samples\gamepad\gamepad.py", line 102, in connect
    if device.device_class == InputDevice.DeviceClass.gamepad and not self.gamepad:
TypeError: object() takes no parameters
```
device_tester.py
```
C:\Panda3D-1.10.0-x64\samples\gamepad>device_tester.py
  File "C:\Panda3D-1.10.0-x64\samples\gamepad\device_tester.py", line 221
    **half_width_entry,
                      ^
SyntaxError: invalid syntax
```

mappingGUI.py (runs, but crashes when a 'Change' button is pressed)
```
C:\Panda3D-1.10.0-x64\samples\gamepad>mappingGUI.py
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "C:\Panda3D-1.10.0-x64\direct\showbase\EventManager.py", line 47, in eventLoopTask
    self.doEvents()
  File "C:\Panda3D-1.10.0-x64\direct\showbase\EventManager.py", line 41, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "C:\Panda3D-1.10.0-x64\direct\showbase\EventManager.py", line 98, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.10.0-x64\direct\showbase\Messenger.py", line 333, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.10.0-x64\direct\showbase\Messenger.py", line 418, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Panda3D-1.10.0-x64\direct\gui\DirectButton.py", line 103, in commandFunc
    self['command'](*self['extraArgs'])
  File "C:\Panda3D-1.10.0-x64\samples\gamepad\mappingGUI.py", line 320, in changeMapping
    self.axisStates.update({device: {axis.axis: axis.value}})
TypeError: object() takes no parameters
:task(error): Exception occurred in PythonTask eventManager
```

@littletooncat was able to get the same errors on Linux, also using an x64 build.

**Comment by rdb** [comment]
I'm guessing you are trying to run the samples with Python 2.7?  These samples may not have been tested with Python 2.7 yet.

**Comment by rdb** [comment]
I've fixed the issues (which were due to an interrogate problem) except for the `device_tester.py` syntax error, which happens because that file makes use of Python 3 syntax to unpack a dict in keyword arguments.

Perhaps someone from the community is willing to do the work to make that file work in Python 2; it doesn't have a high priority for me personally.
