### ISSUE TITLE
Particles: "SpriteAnim" not defined

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#544]
I don't know whether or not this is related to #543.

I usually use sprite-particles, and when attempting to save such particle-systems (whether from the Particle Panel or otherwise), I get the following error in "Particles.py":
`"NameError: global name 'SpriteAnim' is not defined"`

Full error output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/EventManager.py", line 47, in eventLoopTask
    self.doEvents()
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/EventManager.py", line 41, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/EventManager.py", line 100, in processEvent
    messenger.send(eventName)
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/Messenger.py", line 333, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/Messenger.py", line 418, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/thaumaturge/Documents/My Game Projects/Adventuring/ParticleEditor.py", line 1098, in savePtf
    self.particleEffect.saveConfig("particleEffect.ptf")
  File "/usr/local/lib/python2.7/dist-packages/direct/particles/ParticleEffect.py", line 189, in saveConfig
    p.printParams(f, target)
  File "/usr/local/lib/python2.7/dist-packages/direct/particles/Particles.py", line 415, in printParams
    if(anim.getSourceType() == SpriteAnim.STTexture):
NameError: global name 'SpriteAnim' is not defined
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "/home/thaumaturge/Documents/My Game Projects/Adventuring/ParticleEditor.py", line 1936, in <module>
    gameFramework.run()
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/ShowBase.py", line 3109, in run
    self.taskMgr.run()
  File "/usr/local/lib/python2.7/dist-packages/direct/task/Task.py", line 531, in run
    self.step()
  File "/usr/local/lib/python2.7/dist-packages/direct/task/Task.py", line 485, in step
    self.mgr.poll()
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/EventManager.py", line 47, in eventLoopTask
    self.doEvents()
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/EventManager.py", line 41, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/EventManager.py", line 100, in processEvent
    messenger.send(eventName)
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/Messenger.py", line 333, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/usr/local/lib/python2.7/dist-packages/direct/showbase/Messenger.py", line 418, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/thaumaturge/Documents/My Game Projects/Adventuring/ParticleEditor.py", line 1098, in savePtf
    self.particleEffect.saveConfig("particleEffect.ptf")
  File "/usr/local/lib/python2.7/dist-packages/direct/particles/ParticleEffect.py", line 189, in saveConfig
    p.printParams(f, target)
  File "/usr/local/lib/python2.7/dist-packages/direct/particles/Particles.py", line 415, in printParams
    if(anim.getSourceType() == SpriteAnim.STTexture):
NameError: global name 'SpriteAnim' is not defined
```

**Comment by rdb** [comment]
Could you confirm whether the suggested fix of adding `from panda3d.physics import SpriteAnim` to `/usr/local/lib/python2.7/dist-packages/direct/particles/Particles.py` works?
