### ISSUE TITLE
DirectOptionMenu loses item-styling when item-list is changed

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#650]
If a DirectOptionMenu is constructed with "item_" keyword-parameters, at least some of their effect seems to be lost if the menu's item-list is changed. I haven't checked all available "item_" keywords, but it seems that "item_pad" and "item_frameColor" at least are lost.

OS: Ubuntu 18.04.2
Panda version: 1.10.2, I believe.

A short test-program that demonstrates the issue, on my machine at least:
```
from direct.gui.DirectGui import DirectOptionMenu
from panda3d.core import TextNode

from direct.showbase import ShowBase as showBase

itemList1 = ["Kitten", "Cat", "Kitty"]
itemList2 = ["Mew", "Meow", "Mrrr", "Purr"]

class Game(showBase.ShowBase):

    def __init__(self):
        showBase.ShowBase.__init__(self)

        self.accept("escape", self.userExit)

        self.accept("space", self.changeItemList)

        self.menu = DirectOptionMenu(
            scale = 0.1,
            items = itemList1,
            initialitem = -1,
            item_pad = (0.7, 0.7),
            item_frameColor = (0, 1, 0, 1),
            highlightColor = (0, 1, 0.7, 1)
        )

    def changeItemList(self):
        self.menu["items"] = itemList2


app = Game()
app.run()
```
Run the program, noting that the menu's items-buttons are green and heavily padded. Now, press the space-bar; on my machine, the item-list is changed, and the new buttons seem to have the default colour and padding.

**Comment by ArsThaumaturgis** [comment]
If this hasn't already been addressed, I might take this on, along with #651 and #646.

**Comment by ArsThaumaturgis** [comment]
Hmm... Is it considered an error to change the item-styling of a DirectOptionMenu after the menu has been created? I think that I have this thread's issue nearly fixed, but testing it resulted in my bumping into the discovery that setting an "item_" property after the item-list has been changed seems to result in the program crashing, with the following error (in the case of changing "item_frameColor")):
```
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "/home/thaumaturge/Documents/My Game Projects/BugHunt/bugHunt.py", line 46, in <module>
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/direct/showbase/ShowBase.py", line 3109, in run
    self.taskMgr.run()
  File "/usr/local/lib/python3.6/dist-packages/direct/task/Task.py", line 531, in run
    self.step()
  File "/usr/local/lib/python3.6/dist-packages/direct/task/Task.py", line 485, in step
    self.mgr.poll()
  File "/usr/local/lib/python3.6/dist-packages/direct/showbase/EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "/usr/local/lib/python3.6/dist-packages/direct/showbase/EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "/usr/local/lib/python3.6/dist-packages/direct/showbase/EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "/usr/local/lib/python3.6/dist-packages/direct/showbase/Messenger.py", line 333, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/usr/local/lib/python3.6/dist-packages/direct/showbase/Messenger.py", line 418, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/thaumaturge/Documents/My Game Projects/BugHunt/bugHunt.py", line 35, in changeItemVals
    self.menu["item_frameColor"] = (0, 0, 1, 1)
  File "/usr/local/lib/python3.6/dist-packages/direct/gui/DirectOptionMenu.py", line 312, in __setitem__
    DirectButton.__setitem__(self, key, value)
  File "/usr/local/lib/python3.6/dist-packages/direct/gui/DirectGuiBase.py", line 438, in __setitem__
    self.configure(**{key: value})
  File "/usr/local/lib/python3.6/dist-packages/direct/gui/DirectGuiBase.py", line 427, in configure
    func(**options)
  File "/usr/local/lib/python3.6/dist-packages/direct/gui/DirectGuiBase.py", line 331, in configure
    optionInfo = self._optionInfo
AttributeError: 'DirectButton' object has no attribute '_optionInfo'
```
A quick check seems to suggest that this issue wasn't introduced by my changes--although I may be mistaken.

I'm thus not sure of whether this is something that I should look into fixing, or for which I should at least open a new issue.

Here follows a short test-program that demonstrates the issue, on my machine, at least.

After running the program. first press "enter" to change the frame-colour of the items in the menu, then press "space" to change the item-list. All should be fine, save that the styling is lost (which is what I'm working on in this issue).

Next, press "enter" again to once again change the frame-colour with the new item-list. At this point the program should crash.

(Alternatively to the latter instruction, restart the program, then press "space" first, to change the item-list, then press "enter".)
```
from direct.gui.DirectGui import DirectOptionMenu

from direct.showbase import ShowBase as showBase


class Game(showBase.ShowBase):

    def __init__(self):
        showBase.ShowBase.__init__(self)

        self.accept("escape", self.userExit)

        self.accept("space", self.changeItemList)

        self.accept("enter", self.changeItemVals)

        self.itemListIndex = 0
        self.itemLists = [
                            ["Kitten", "Cat", "Kitty"],
                            ["Mouser"],
                            ["Purr", "Meow"]
                         ]

        self.menu = DirectOptionMenu(
            scale = 0.1,
            pos = (-1, 0, 0),
            items = self.itemLists[0],
            item_frameColor = (0, 1, 0, 1),
            popupMarker_pos = (0, 0, 0)
        )

    def changeItemVals(self):
        self.menu["item_frameColor"] = (0, 0, 1, 1)

    def changeItemList(self):
        self.itemListIndex = (self.itemListIndex + 1) % len(self.itemLists)
        self.menu["items"] = self.itemLists[self.itemListIndex]
        print ("Changed item-list to:", self.itemLists[self.itemListIndex])

app = Game()
app.run()
```

**Comment by ArsThaumaturgis** [comment]
Okay, I think that I've found the source of that crash: in short, it seems that items weren't being cleaned up when a new set was created, thus potentially leading DirectGUI to attempt to configure a component that had been removed.

I have a fix for this, but it may not be the best approach. Nevertheless, I'll likely create a pull request for it once I've created one for the changes made for this issue, I think.

**Comment by ArsThaumaturgis** [comment]
Here is a pull request for this issue: https://github.com/panda3d/panda3d/pull/655

And a short test-program to demonstrate the changes:

Press "enter" to make the item-padding increase, and to cycle through item-frame-colours. Press "space" to cycle through a set of item-lists, which should now hopefully retain the altered item-styling that results from pressing "enter".
```
from direct.gui.DirectGui import DirectOptionMenu

from direct.showbase import ShowBase as showBase


class Game(showBase.ShowBase):

    def __init__(self):
        showBase.ShowBase.__init__(self)

        self.accept("escape", self.userExit)

        self.accept("space", self.changeItemList)

        self.accept("enter", self.changeItemVals)

        self.itemListIndex = 0
        self.itemLists = [
                            ["Kitten", "Cat", "Kitty"],
                            ["Mouser"],
                            ["Purr", "Meow"]
                         ]

        self.frameColourIndex = 0
        self.frameColours = [
                                (0, 1, 0, 1),
                                (0, 0, 1, 1),
                                (1, 0, 1, 1)
                            ]

        self.menu = DirectOptionMenu(
            scale = 0.1,
            pos = (-1, 0, 0),
            items = self.itemLists[0],
            item_pad = (0.5, 0.5),
            item_frameColor = self.frameColours[0],
            highlightColor = (0, 1, 0.7, 1),
            popupMarker_pos = (0, 0, 0),
            command = self.itemSelected,
        )

    def changeItemVals(self):
        self.menu["item_pad"] = (self.menu["item_pad"][0] + 0.1, self.menu["item_pad"][1] + 0.1)

        self.frameColourIndex = (self.frameColourIndex + 1) % len(self.frameColours)
        self.menu["item_frameColor"] = self.frameColours[self.frameColourIndex]

    def changeItemList(self):
        self.itemListIndex = (self.itemListIndex + 1) % len(self.itemLists)
        self.menu["items"] = self.itemLists[self.itemListIndex]
        print ("Changed item-list to:", self.itemLists[self.itemListIndex])

    def itemSelected(self, item):
        print ("Selected:", item)

app = Game()
app.run()
```
