### ISSUE TITLE
Error when converting Maya 2018 to egg when Panda is installed from pip

### ISSUE THREAD

**Issue by MaxwellSalmon** [panda3d/panda3d#709]
When converting a Maya 2018 binary file to egg using `maya2egg2018` this error occurs:

    MAYA_LOCATION: C:\Program Files\Autodesk\Maya2018
    Fatal Python error: initfsencoding: unable to load the file system codec
    Traceback (most recent call last):
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 906, in _find_spec
      File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
      File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
      File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
      File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
      File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
      File "C:\Program Files\Autodesk\Maya2018\bin\python27.zip\encodings\__init__.py", line 123
        raise CodecRegistryError,\
                        ^
    SyntaxError: invalid syntax
    Program exited with status 3221226505

However, it seems this only happens when Panda3D is installed via pip.

**Comment by rdb** [comment]
Did you install Panda3D into a virtualenv for this to happen, or does it also happen when using pip without venv?

Are you available to run some tests for possible solutions?

**Comment by rdb** [comment]
I figured it out (tested with the Maya 2020 trial): it's invoking the wrong `maya2egg#_bin.exe` under the hood, namely the wrapper that is in the Scripts folder (which is on the PATH) as opposed to the one inside the `panda3d_tools` package.  This is pretty easy to fix.

Incidentally, we should not be shipping a wrapper of the _bin.exe versions of these utilities in the Scripts/bin folder.
