### ISSUE TITLE
DS_interrupt doesn't interrupt threaded task chains

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#710]
A task belonging to a threaded taskchain raising an exception is restarted again and again instead of being aborted. This is similar to #692 though in this case it happens with threaded taskchains (In the example code below, if numThread is set to 0 the exception is properly caught by the taskchain and reported to the task manager)

Here is the test code :

```python
#!/usr/bin/env python

from direct.showbase.ShowBase import ShowBase
from panda3d.core import PandaSystem

import platform

def processTask(task):
    print("Hello")
    raise Exception()
    print("Goodbye")
    return task.done

base = ShowBase()

print("Python version:", platform.python_version())
print("Panda version: %s (%s)" % (PandaSystem.getVersionString(), PandaSystem.getGitCommit()))

base.taskMgr.setupTaskChain("chain",
                            numThreads = 1,
                            tickClock = False,
                            threadPriority = None,
                            frameBudget = -1,
                            frameSync = False,
                            timeslicePriority = True)

process_task = base.taskMgr.add(processTask, 'ProcessTask', taskChain="chain")

base.run()
```

Here is the output :
<pre>
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Python version: 3.5.2
Panda version: 1.10.4.1 (1318fd80d7fd48a84394ee86bad6a57c245206e1)
Hello
:thread(error): Exception occurred within Thread TaskManager_chain_0
Traceback (most recent call last):
  File "tests/test_tc.py", line 10, in processTask
    raise Exception()
Exception
:task(error): Exception occurred in PythonTask ProcessTask
Hello
:thread(error): Exception occurred within Thread TaskManager_chain_0
Traceback (most recent call last):
  File "tests/test_tc.py", line 10, in processTask
    raise Exception()
Exception
:task(error): Exception occurred in PythonTask ProcessTask
Hello
:thread(error): Exception occurred within Thread TaskManager_chain_0
Traceback (most recent call last):
  File "tests/test_tc.py", line 10, in processTask
    raise Exception()
Exception
:task(error): Exception occurred in PythonTask ProcessTask
Hello
</pre>

A workaround is to wrap the task code by a catch-all and raise SystemExit exception :

```python
        try:
            # Task Code here...
        except Exception:
            traceback.print_exc()
            raise SystemExit
```

**Comment by el-dee** [comment]
Bumping this as with "recent" Panda3D 1.11 (I'm sorry I didn't notice when it has changed) even raising `SystemExit` (or using `exit()`) does not stop the program, the task keeps getting spawned again and again.

Note that when raising `SystemExit` or using `exit()` no trace at all is reported in the console, just an endless stream of 

<pre>
Hello
Goodbye
Hello
Goodbye
Hello
Goodbye
Hello
Goodbye
Hello
Goodbye
Hello
Goodbye
Hello
...
</pre>
