### ISSUE TITLE
FreezeTool.py: 'mdef' is not defined

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#721]
As with #720, this was encountered while building a small test-program with a less-than-proper "setup.py" file.

I encountered this error:

```text
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    'win_amd64'
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/commands.py", line 1414, in run
    self.run_command('build_apps')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/commands.py", line 380, in run
    self.build_runtimes(platform, True)
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/commands.py", line 709, in build_runtimes
    create_runtime(appname, scriptname, False)
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/commands.py", line 639, in create_runtime
    freezer.addModule(incmod)
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/FreezeTool.py", line 1042, in addModule
    guess, fromSource, text))
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/FreezeTool.py", line 1002, in _gatherSubmodules
    fromSource = fromSource, text = text)
NameError: name 'mdef' is not defined
```

Looking at the indicated code, I _think_ that this is a simple case of a missing "s": a little distance above that line, a variable named "mdefs" is defined, and the same is used elsewhere. However, take that with a grain of salt, as I haven't closely examined the code!

**Comment by Moguri** [comment]
You are correct that this should be `mdefs` and not `mdef`. Feel free to submit a PR; I will also add this to my todo list along with all of the other stuff I will "get to eventually."

Do you have an example of a setup.py that can cause this error?

**Comment by ArsThaumaturgis** [comment]
It looks like an easy way to reproduce it is to have the "setup.py" file specify an "include_module" that doesn't exist. (I don't know whether other means might produce it, too.)

So, presuming that you have an application with a source file named "bugHunt.py", and **don't** have a module with the pattern "Adventuring.Cutscenes.*", the following should work:

```python
from setuptools import setup

setup(
    name = "Bug Hunt",
    options = {
        "build_apps" : {
            "include_modules" : {
                "*" : ["Adventuring.Cutscenes.*"]
            },
            "gui_apps": {
                "Bug Hunt" : "bugHunt.py"
            },
            "platforms": [
                "manylinux1_x86_64",
            ],
        }
    }
)
```

As to a pull request... I've generally found those to be a bit of a pain, and I don't relish the idea of dealing with them for the sake of a single-character edit. That said, I am a bit tired and a little bit headachy right now, which may be affecting my mood, so I may reconsider later.

**Comment by Moguri** [comment]
Thanks for the repro case; I'll try to take a look later this week or the weekend.

**Comment by ArsThaumaturgis** [comment]
Not a problem; it's my pleasure. ^_^

**Comment by rdb** [comment]
> As to a pull request... I've generally found those to be a bit of a pain, and I don't relish the idea of dealing with them for the sake of a single-character edit.
That's fair enough, but note that for simple edits, it's possible to create pull requests via the GitHub web interface by simply clicking the Edit button on a file.

**Comment by ArsThaumaturgis** [comment]
> That's fair enough, but note that for simple edits, it's possible to create pull requests via the GitHub web interface by simply clicking the Edit button on a file.

Ah, that's very good to know--I wasn't aware of that! Thank you for telling me. ^_^

**Comment by Moguri** [comment]
Assigning this to myself so I remember to look at and test out the PR.
