### ISSUE TITLE
Datetime's issue

### ISSUE THREAD

**Issue by cflavio** [panda3d/panda3d#728]
Hi! I have the following code (Panda3D 1.10.4.1):

```
import datetime, direct.showbase.ShowBase

d1 = datetime.datetime.strptime(
    'Sat, 31 Aug 2019 00:00:00 +0200',
    '%a, %d %b %Y %H:%M:%S %z')
print(d1)

class App(direct.showbase.ShowBase.ShowBase):
    def __init__(self):
        direct.showbase.ShowBase.ShowBase.__init__(self)
        d2 = datetime.datetime.strptime(
            'Sat, 31 Aug 2019 00:00:00 +0200',
            '%a, %d %b %Y %H:%M:%S %z')
        print(d2)

App().run()
```

The arguments received by _strptime_ are the same. But, while the first _strptime_ works well and I can print the result, the second one crashes.

```
$ python main.py 
2019-08-31 00:00:00+02:00
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    App().run()
  File "main.py", line 13, in __init__
    '%a, %d %b %Y %H:%M:%S %z')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Sat, 31 Aug 2019 00:00:00 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
```

**Comment by rdb** [comment]
Hmm, it works for me in Python 3.7—might it be dependent on your system locale?  Perhaps initializing Panda causes the locale to be initialized?

**Comment by cflavio** [comment]
I don't know if this is the correct way to check it. I have modified the code for printing the locale:

```
import datetime, direct.showbase.ShowBase, os

d1 = datetime.datetime.strptime(
    'Sat, 31 Aug 2019 00:00:00 +0200',
    '%a, %d %b %Y %H:%M:%S %z')
print(d1)
os.system('locale')

class App(direct.showbase.ShowBase.ShowBase):
    def __init__(self):
        direct.showbase.ShowBase.ShowBase.__init__(self)
        os.system('locale')
        d2 = datetime.datetime.strptime(
            'Sat, 31 Aug 2019 00:00:00 +0200',
            '%a, %d %b %Y %H:%M:%S %z')
        print(d2)

App().run()
```

I get this:

```
$ python main.py 
2019-08-31 00:00:00+02:00
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=it_IT.UTF-8
LC_NAME=it_IT.UTF-8
LC_ADDRESS=it_IT.UTF-8
LC_TELEPHONE=it_IT.UTF-8
LC_MEASUREMENT=it_IT.UTF-8
LC_IDENTIFICATION=it_IT.UTF-8
LC_ALL=
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=it_IT.UTF-8
LC_NAME=it_IT.UTF-8
LC_ADDRESS=it_IT.UTF-8
LC_TELEPHONE=it_IT.UTF-8
LC_MEASUREMENT=it_IT.UTF-8
LC_IDENTIFICATION=it_IT.UTF-8
LC_ALL=
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    App().run()
  File "main.py", line 15, in __init__
    '%a, %d %b %Y %H:%M:%S %z')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Sat, 31 Aug 2019 00:00:00 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
```

**Comment by cflavio** [comment]
Ok, I have done other experiments, thank you very much for your suggestion! This works:

```
import datetime, direct.showbase.ShowBase, os, locale                                                     
                                                                                                          
d1 = datetime.datetime.strptime('31 Aug 2019','%d %b %Y')                                                 
print(d1)                                                                                                 
                                                                                                          
class App(direct.showbase.ShowBase.ShowBase):                                                             
    def __init__(self):                                                                                   
        direct.showbase.ShowBase.ShowBase.__init__(self)                                                  
        locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')                                                    
        d2 = datetime.datetime.strptime('31 Aug 2019', '%d %b %Y')                                        
        print(d2)                                                                                         
                                                                                                          
App().run()
```

**Comment by rdb** [comment]
I think we should close this as this isn't really an issue with Panda, but simply an awkward effect of how the C setlocale function works, but I'm happy to collect other opinions on this—it could perhaps be argued that Panda should not touch setlocale, or something like that.

**Comment by cflavio** [comment]
In my experience this behavior has been counter-intuitive (it reminds me something like sequential coupling). Anyway, I don't know why Panda3D uses setlocale (what is the reason?). If there is a good reason then I presume that documenting it in the manual would be enough.

**Comment by rdb** [comment]
The reason why Panda uses setlocale is that X11 requires it to get international keyboard support.

However, after initializing X11, we could be setting the locale to the default setting again.

**Comment by rdb** [comment]
I'm fixing this, but targeting this for 1.11, since users may rely on the existing behaviour.  It is possible to work around the existing behaviour using an explicit `setlocale(locale.LC_TIME, "C")` call.
