### ISSUE TITLE
setuptools: missing import importlib in FreezeTool.py

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#836]
While testing building my app, I encountered this error :

    File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2353, in load_module
        marshal_data = importlib._bootstrap_external._validate_bytecode_header(fp.read())
    NameError: name 'importlib' is not defined

It was triggered by an external module containing old Python2 .pyc files (by mistake). I guess FreezeTool though it was a binary only module and tried to load all the pyc files and this triggered the error. Simply adding ```import importlib``` at the top of the file solved the problem, but I'm not sure if it's valid far all the supported versions of Python (and it is definitively not supported by Python2).

The full backtrace is :

<pre>
Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    setup(**config)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/share/panda3d/direct/dist/commands.py", line 391, in run
    self.build_runtimes(platform, True)
  File "/usr/share/panda3d/direct/dist/commands.py", line 720, in build_runtimes
    create_runtime(appname, scriptname, False)
  File "/usr/share/panda3d/direct/dist/commands.py", line 653, in create_runtime
    freezer.done(addStartupModules=True)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 1113, in done
    self.__loadModule(mdef)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 1223, in __loadModule
    self.mf.load_module(mdef.moduleName, fp, pathname, stuff)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2367, in load_module
    self.scan_code(co, m)
  File "/usr/lib/python3.5/modulefinder.py", line 375, in scan_code
    self._safe_import_hook(name, m, fromlist, level=0)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2379, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/lib/python3.5/modulefinder.py", line 123, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/lib/python3.5/modulefinder.py", line 200, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/lib/python3.5/modulefinder.py", line 271, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2367, in load_module
    self.scan_code(co, m)
  File "/usr/lib/python3.5/modulefinder.py", line 398, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2379, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/lib/python3.5/modulefinder.py", line 123, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/lib/python3.5/modulefinder.py", line 200, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/lib/python3.5/modulefinder.py", line 271, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2367, in load_module
    self.scan_code(co, m)
  File "/usr/lib/python3.5/modulefinder.py", line 398, in scan_code
    self._safe_import_hook(name, m, fromlist, level=level)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2379, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/lib/python3.5/modulefinder.py", line 122, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/lib/python3.5/modulefinder.py", line 178, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/lib/python3.5/modulefinder.py", line 271, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2367, in load_module
    self.scan_code(co, m)
  File "/usr/lib/python3.5/modulefinder.py", line 375, in scan_code
    self._safe_import_hook(name, m, fromlist, level=0)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2379, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/lib/python3.5/modulefinder.py", line 122, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/lib/python3.5/modulefinder.py", line 178, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/lib/python3.5/modulefinder.py", line 271, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2332, in load_module
    m = self.load_package(fqname, pathname)
  File "/usr/lib/python3.5/modulefinder.py", line 424, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/share/panda3d/direct/dist/FreezeTool.py", line 2353, in load_module
    marshal_data = importlib._bootstrap_external._validate_bytecode_header(fp.read())
NameError: name 'importlib' is not defined
</pre>

**Comment by rdb** [comment]
Thanks.  This method was new in Python 3.5.  We should be doing different things depending on the Python version:
https://github.com/python/cpython/blob/3.4/Lib/modulefinder.py#L291-L295
https://github.com/python/cpython/blob/3.3/Lib/modulefinder.py#L287-L290
https://github.com/python/cpython/blob/2.7/Lib/modulefinder.py#L311-L314

Adding an `import importlib` to the top can't hurt (the module exists in Python 2.7, but didn't have these sub-modules).

**Comment by rdb** [comment]
Interestingly, this is also broken in Python 3.8, where they changed it again:
https://github.com/python/cpython/blob/3.8/Lib/modulefinder.py#L345-L351
