### ISSUE TITLE
The animation doesn't play. Format .X

### ISSUE THREAD

**Issue by serkkz** [panda3d/panda3d#850]
`from direct.showbase.ShowBase import ShowBase
from direct.actor.Actor import Actor
 
class MyApp(ShowBase):
 
    def __init__(self):
        ShowBase.__init__(self)

        self.DemoAnim = Actor("model.X", {"Anim":"model.X",})
        self.DemoAnim.reparentTo(render)
        self.DemoAnim.loop('Anim', 'Anim-2')

app = MyApp()
app.run()`

This works for Panda3D-1.8.1, but it no longer works in the latest version.

[Format.X.zip](https://github.com/panda3d/panda3d/files/4083071/Format.X.zip)

**Comment by rdb** [comment]
If you use x2egg, and load the resulting .egg file, is it still a problem?

**Comment by serkkz** [comment]
Yes, this works for x2egg. However, I don't think this is the way out. It worked and should work now, without any crutches

**Comment by rdb** [comment]
In Panda3D 1.8.1, loading an .x file via Panda worked by using x2egg under the hood and then loading the resulting .egg file.  Panda3D can now load .x files via the Assimp library, directly to the native structures, without the intermediate step.  We should investigate why .x files loaded via Assimp do not contain animations.

**Comment by serkkz** [comment]
Is it possible to explicitly indicate the Assimp ban?

**Comment by rdb** [comment]
You can remove the `load-file-type p3assimp` line from your Config.prc file.

**Comment by serkkz** [comment]
I thought about it, but there is no such line.

**Comment by rdb** [comment]
Sorry, it is in the `Confauto.prc` file.

**Comment by serkkz** [comment]
No effect.

**Comment by rdb** [comment]
You will need to delete the model cache after changing this setting.

**Comment by serkkz** [comment]
Works, however, there are warnings.

```
:egg2pg(warning): AnimBundle model does not specify a frame rate.
:egg2pg(warning): AnimBundle model does not specify a frame rate.
```

**Comment by serkkz** [comment]
```
:egg2pg(warning): AnimBundle model does not specify a frame rate.
:egg2pg(warning): AnimBundle model does not specify a frame rate.
:Actor(warning): model.X is not a character!
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    app = MyApp()
  File "main.py", line 11, in __init__
    self.DemoAnim.loop('Anim', 'Anim-2')
  File "c:\Panda3D\direct\actor\Actor.py", line 1554, in loop
    for control in self.getAnimControls(animName, partName):
  File "c:\Panda3D\direct\actor\Actor.py", line 1848, in getAnimControls
    allowAsyncBind = allowAsyncBind)
  File "c:\Panda3D\direct\actor\Actor.py", line 2352, in __bindAnimToPart
    bundle = self.__commonBundleHandles[subpartDef.truePartName].getBundle()
KeyError: 'modelRoot'
```

It seems that the behavior is different after deleting the cache.

**Comment by serkkz** [comment]
Four starts and the animation is no longer played.
