### ISSUE TITLE
Exception - privPostEvent in IntervalManager

### ISSUE THREAD

**Issue by alek5k** [panda3d/panda3d#961]
Hi, I get the following exception when running my code and can't seem to find any more information about it. 

Panda3D Version (installed using pip): 
panda3d==1.10.6

Exception:
```
Traceback (most recent call last):
  File "\venv\lib\site-packages\direct\showbase\ShowBase.py", line 1964, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "\venv\lib\site-packages\direct\interval\IntervalManager.py", line 95, in step
    self.__doPythonCallbacks()
  File "\venv\lib\site-packages\direct\interval\IntervalManager.py", line 123, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
AttributeError: 'NoneType' object has no attribute 'privPostEvent'
:task(error): Exception occurred in PythonTask ivalLoop
Traceback (most recent call last):
  File "Main.py", line 500, in <module>
    app.run()
  File "\venv\lib\site-packages\direct\showbase\ShowBase.py", line 3152, in run
    self.taskMgr.run()
  File "\venv\lib\site-packages\direct\task\Task.py", line 541, in run
    self.step()
  File "\venv\lib\site-packages\direct\task\Task.py", line 495, in step
    self.mgr.poll()
  File "\venv\lib\site-packages\direct\showbase\ShowBase.py", line 1964, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "\venv\lib\site-packages\direct\interval\IntervalManager.py", line 95, in step
    self.__doPythonCallbacks()
  File "\venv\lib\site-packages\direct\interval\IntervalManager.py", line 123, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
AttributeError: 'NoneType' object has no attribute 'privPostEvent'
```

Perhaps it might be relevant that I am running the clock in non-realtime mode:
```
clock_setting = 0.01
builtins.globalClock.setMode(builtins.globalClock.MNonRealTime)
builtins.globalClock.setDt(clock_setting)
```

All usage of interval functions are wrapped inside my ActionQueue class. I am fairly confident that the `clear` method is not being called when the exception occurs.

ActionQueue.py:
```
from direct.interval.IntervalGlobal import Sequence, Parallel, Func

# An action queue which lets you create multiple intervals and executes them once each have completed
class ActionQueue:
    def __init__(self, intervalType=Sequence):
        self.intervalType = intervalType
        self.executing = False
        self.executing_interval = None
        self.onCompleteCallbackList = []
        self.onStartedCallbackList = []
        self.intervalStepList = []
        self.intervalList = []

    def addStep(self, *intervalStep):
        for step in intervalStep:
            self.intervalStepList.append(step)
    
    def onComplete(self):
        self.executing = False
        self.executing_interval = None
        self.runQueue()

    def runQueue(self):
        if not self.executing and len(self.intervalList) > 0:
            next_interval = self.intervalList.pop(0)
            self.executing = True
            self.executing_interval = next_interval
            next_interval.start()

    def clear(self):
        if self.executing_interval:
            self.executing_interval.pause()
            # self.executing_interval.finish() # calls all the finalization functions
        self.intervalList = []
        self.intervalStepList = []
        self.executing = False

    def execute(self):

        interval = self.intervalType()
        self.intervalList.append(interval)

        for callback in self.onStartedCallbackList:
            interval.append(Func(callback))

        for intervalStep in self.intervalStepList:
            interval.append(intervalStep)

        self.intervalStepList = []

        for callback in self.onCompleteCallbackList:
            interval.append(Func(callback))
        
        interval.append(Func(self.onComplete))

        self.runQueue()

    def addOnCompleteCallback(self, callback):
        self.onCompleteCallbackList.append(callback)

    def addOnStartedCallback(self, callback):
        self.onStartedCallbackList.append(callback)

```

Example usage of ActionQueue.py
```
actionQueue = ActionQueue()
actionQueue.addStep(Func(_faceDirection, point))
posInterval1 = LerpPosInterval(self, time / speed_factor, point)
actionQueue.addStep(posInterval1)
actionQueue.execute()
```

**Comment by alek5k** [comment]
I have debugged the `IntervalManager` class and I have found the following information.

The value of `index` is `2`:

![IRWfKtfRUG](https://user-images.githubusercontent.com/20435565/85373395-8af06480-b576-11ea-87da-f81ed8951dc0.png)


`self.ivals[2]` is a `Sequence`:

![BknkPsVXNv](https://user-images.githubusercontent.com/20435565/85373220-4d8bd700-b576-11ea-9b76-d28b309ea6b8.png)

Seems like `self.ivals[2]` does not have a `privPostEvent` method:

![xia3VY71ck](https://user-images.githubusercontent.com/20435565/85373297-68f6e200-b576-11ea-9d01-0a8347f4b630.png)

Let me know if there's anything else I should check.

**Comment by alek5k** [comment]
I have a feeling this occurs when the sequence gets too long. Is there a maximum limit imposed on number of items within the sequence? It seems I was calling a long list of functions within the sequence.

**Comment by rdb** [comment]
Could you try and produce a minimal reproduction case that I can run to see the error for myself?

**Comment by alek5k** [comment]
Hi @rdb , I could not easily make a minimal reproduction case, but I did find a bug in my code that made my Interval instances grow really quickly (many thousands of sequences), so I think it may have to do with a maximum interval size in memory (some kind of overflow?). I did not get a chance to investigate further, but hope this helps if someone else runs into the issue.
